// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"
	"uno/domain/ports"

	mock "github.com/stretchr/testify/mock"
)

// NewShoppingListItemRepo creates a new instance of ShoppingListItemRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShoppingListItemRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShoppingListItemRepo {
	mock := &ShoppingListItemRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShoppingListItemRepo is an autogenerated mock type for the ShoppingListItemRepo type
type ShoppingListItemRepo struct {
	mock.Mock
}

type ShoppingListItemRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ShoppingListItemRepo) EXPECT() *ShoppingListItemRepo_Expecter {
	return &ShoppingListItemRepo_Expecter{mock: &_m.Mock}
}

// CreateShoppingListItem provides a mock function for the type ShoppingListItemRepo
func (_mock *ShoppingListItemRepo) CreateShoppingListItem(ctx context.Context, item model.NewShoppingListItem) (model.ShoppingListItem, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateShoppingListItem")
	}

	var r0 model.ShoppingListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.NewShoppingListItem) (model.ShoppingListItem, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.NewShoppingListItem) model.ShoppingListItem); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Get(0).(model.ShoppingListItem)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.NewShoppingListItem) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShoppingListItemRepo_CreateShoppingListItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShoppingListItem'
type ShoppingListItemRepo_CreateShoppingListItem_Call struct {
	*mock.Call
}

// CreateShoppingListItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item model.NewShoppingListItem
func (_e *ShoppingListItemRepo_Expecter) CreateShoppingListItem(ctx interface{}, item interface{}) *ShoppingListItemRepo_CreateShoppingListItem_Call {
	return &ShoppingListItemRepo_CreateShoppingListItem_Call{Call: _e.mock.On("CreateShoppingListItem", ctx, item)}
}

func (_c *ShoppingListItemRepo_CreateShoppingListItem_Call) Run(run func(ctx context.Context, item model.NewShoppingListItem)) *ShoppingListItemRepo_CreateShoppingListItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.NewShoppingListItem
		if args[1] != nil {
			arg1 = args[1].(model.NewShoppingListItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShoppingListItemRepo_CreateShoppingListItem_Call) Return(shoppingListItem model.ShoppingListItem, err error) *ShoppingListItemRepo_CreateShoppingListItem_Call {
	_c.Call.Return(shoppingListItem, err)
	return _c
}

func (_c *ShoppingListItemRepo_CreateShoppingListItem_Call) RunAndReturn(run func(ctx context.Context, item model.NewShoppingListItem) (model.ShoppingListItem, error)) *ShoppingListItemRepo_CreateShoppingListItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteShoppingListItem provides a mock function for the type ShoppingListItemRepo
func (_mock *ShoppingListItemRepo) DeleteShoppingListItem(ctx context.Context, itemID string) error {
	ret := _mock.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteShoppingListItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, itemID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ShoppingListItemRepo_DeleteShoppingListItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteShoppingListItem'
type ShoppingListItemRepo_DeleteShoppingListItem_Call struct {
	*mock.Call
}

// DeleteShoppingListItem is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID string
func (_e *ShoppingListItemRepo_Expecter) DeleteShoppingListItem(ctx interface{}, itemID interface{}) *ShoppingListItemRepo_DeleteShoppingListItem_Call {
	return &ShoppingListItemRepo_DeleteShoppingListItem_Call{Call: _e.mock.On("DeleteShoppingListItem", ctx, itemID)}
}

func (_c *ShoppingListItemRepo_DeleteShoppingListItem_Call) Run(run func(ctx context.Context, itemID string)) *ShoppingListItemRepo_DeleteShoppingListItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShoppingListItemRepo_DeleteShoppingListItem_Call) Return(err error) *ShoppingListItemRepo_DeleteShoppingListItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ShoppingListItemRepo_DeleteShoppingListItem_Call) RunAndReturn(run func(ctx context.Context, itemID string) error) *ShoppingListItemRepo_DeleteShoppingListItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllShoppingListItems provides a mock function for the type ShoppingListItemRepo
func (_mock *ShoppingListItemRepo) GetAllShoppingListItems(ctx context.Context) ([]ports.ShoppingListItemWithCreator, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllShoppingListItems")
	}

	var r0 []ports.ShoppingListItemWithCreator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ports.ShoppingListItemWithCreator, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ports.ShoppingListItemWithCreator); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.ShoppingListItemWithCreator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShoppingListItemRepo_GetAllShoppingListItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllShoppingListItems'
type ShoppingListItemRepo_GetAllShoppingListItems_Call struct {
	*mock.Call
}

// GetAllShoppingListItems is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ShoppingListItemRepo_Expecter) GetAllShoppingListItems(ctx interface{}) *ShoppingListItemRepo_GetAllShoppingListItems_Call {
	return &ShoppingListItemRepo_GetAllShoppingListItems_Call{Call: _e.mock.On("GetAllShoppingListItems", ctx)}
}

func (_c *ShoppingListItemRepo_GetAllShoppingListItems_Call) Run(run func(ctx context.Context)) *ShoppingListItemRepo_GetAllShoppingListItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ShoppingListItemRepo_GetAllShoppingListItems_Call) Return(shoppingListItemWithCreators []ports.ShoppingListItemWithCreator, err error) *ShoppingListItemRepo_GetAllShoppingListItems_Call {
	_c.Call.Return(shoppingListItemWithCreators, err)
	return _c
}

func (_c *ShoppingListItemRepo_GetAllShoppingListItems_Call) RunAndReturn(run func(ctx context.Context) ([]ports.ShoppingListItemWithCreator, error)) *ShoppingListItemRepo_GetAllShoppingListItems_Call {
	_c.Call.Return(run)
	return _c
}
