// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewSiteFeedbackRepo creates a new instance of SiteFeedbackRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSiteFeedbackRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SiteFeedbackRepo {
	mock := &SiteFeedbackRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SiteFeedbackRepo is an autogenerated mock type for the SiteFeedbackRepo type
type SiteFeedbackRepo struct {
	mock.Mock
}

type SiteFeedbackRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *SiteFeedbackRepo) EXPECT() *SiteFeedbackRepo_Expecter {
	return &SiteFeedbackRepo_Expecter{mock: &_m.Mock}
}

// CreateSiteFeedback provides a mock function for the type SiteFeedbackRepo
func (_mock *SiteFeedbackRepo) CreateSiteFeedback(ctx context.Context, feedback model.SiteFeedback) (model.SiteFeedback, error) {
	ret := _mock.Called(ctx, feedback)

	if len(ret) == 0 {
		panic("no return value specified for CreateSiteFeedback")
	}

	var r0 model.SiteFeedback
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.SiteFeedback) (model.SiteFeedback, error)); ok {
		return returnFunc(ctx, feedback)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.SiteFeedback) model.SiteFeedback); ok {
		r0 = returnFunc(ctx, feedback)
	} else {
		r0 = ret.Get(0).(model.SiteFeedback)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.SiteFeedback) error); ok {
		r1 = returnFunc(ctx, feedback)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SiteFeedbackRepo_CreateSiteFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSiteFeedback'
type SiteFeedbackRepo_CreateSiteFeedback_Call struct {
	*mock.Call
}

// CreateSiteFeedback is a helper method to define mock.On call
//   - ctx context.Context
//   - feedback model.SiteFeedback
func (_e *SiteFeedbackRepo_Expecter) CreateSiteFeedback(ctx interface{}, feedback interface{}) *SiteFeedbackRepo_CreateSiteFeedback_Call {
	return &SiteFeedbackRepo_CreateSiteFeedback_Call{Call: _e.mock.On("CreateSiteFeedback", ctx, feedback)}
}

func (_c *SiteFeedbackRepo_CreateSiteFeedback_Call) Run(run func(ctx context.Context, feedback model.SiteFeedback)) *SiteFeedbackRepo_CreateSiteFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.SiteFeedback
		if args[1] != nil {
			arg1 = args[1].(model.SiteFeedback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SiteFeedbackRepo_CreateSiteFeedback_Call) Return(siteFeedback model.SiteFeedback, err error) *SiteFeedbackRepo_CreateSiteFeedback_Call {
	_c.Call.Return(siteFeedback, err)
	return _c
}

func (_c *SiteFeedbackRepo_CreateSiteFeedback_Call) RunAndReturn(run func(ctx context.Context, feedback model.SiteFeedback) (model.SiteFeedback, error)) *SiteFeedbackRepo_CreateSiteFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSiteFeedbacks provides a mock function for the type SiteFeedbackRepo
func (_mock *SiteFeedbackRepo) GetAllSiteFeedbacks(ctx context.Context) ([]model.SiteFeedback, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSiteFeedbacks")
	}

	var r0 []model.SiteFeedback
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.SiteFeedback, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.SiteFeedback); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SiteFeedback)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SiteFeedbackRepo_GetAllSiteFeedbacks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSiteFeedbacks'
type SiteFeedbackRepo_GetAllSiteFeedbacks_Call struct {
	*mock.Call
}

// GetAllSiteFeedbacks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SiteFeedbackRepo_Expecter) GetAllSiteFeedbacks(ctx interface{}) *SiteFeedbackRepo_GetAllSiteFeedbacks_Call {
	return &SiteFeedbackRepo_GetAllSiteFeedbacks_Call{Call: _e.mock.On("GetAllSiteFeedbacks", ctx)}
}

func (_c *SiteFeedbackRepo_GetAllSiteFeedbacks_Call) Run(run func(ctx context.Context)) *SiteFeedbackRepo_GetAllSiteFeedbacks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SiteFeedbackRepo_GetAllSiteFeedbacks_Call) Return(siteFeedbacks []model.SiteFeedback, err error) *SiteFeedbackRepo_GetAllSiteFeedbacks_Call {
	_c.Call.Return(siteFeedbacks, err)
	return _c
}

func (_c *SiteFeedbackRepo_GetAllSiteFeedbacks_Call) RunAndReturn(run func(ctx context.Context) ([]model.SiteFeedback, error)) *SiteFeedbackRepo_GetAllSiteFeedbacks_Call {
	_c.Call.Return(run)
	return _c
}

// GetSiteFeedbackByID provides a mock function for the type SiteFeedbackRepo
func (_mock *SiteFeedbackRepo) GetSiteFeedbackByID(ctx context.Context, feedbackID string) (model.SiteFeedback, error) {
	ret := _mock.Called(ctx, feedbackID)

	if len(ret) == 0 {
		panic("no return value specified for GetSiteFeedbackByID")
	}

	var r0 model.SiteFeedback
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.SiteFeedback, error)); ok {
		return returnFunc(ctx, feedbackID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.SiteFeedback); ok {
		r0 = returnFunc(ctx, feedbackID)
	} else {
		r0 = ret.Get(0).(model.SiteFeedback)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, feedbackID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SiteFeedbackRepo_GetSiteFeedbackByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSiteFeedbackByID'
type SiteFeedbackRepo_GetSiteFeedbackByID_Call struct {
	*mock.Call
}

// GetSiteFeedbackByID is a helper method to define mock.On call
//   - ctx context.Context
//   - feedbackID string
func (_e *SiteFeedbackRepo_Expecter) GetSiteFeedbackByID(ctx interface{}, feedbackID interface{}) *SiteFeedbackRepo_GetSiteFeedbackByID_Call {
	return &SiteFeedbackRepo_GetSiteFeedbackByID_Call{Call: _e.mock.On("GetSiteFeedbackByID", ctx, feedbackID)}
}

func (_c *SiteFeedbackRepo_GetSiteFeedbackByID_Call) Run(run func(ctx context.Context, feedbackID string)) *SiteFeedbackRepo_GetSiteFeedbackByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SiteFeedbackRepo_GetSiteFeedbackByID_Call) Return(siteFeedback model.SiteFeedback, err error) *SiteFeedbackRepo_GetSiteFeedbackByID_Call {
	_c.Call.Return(siteFeedback, err)
	return _c
}

func (_c *SiteFeedbackRepo_GetSiteFeedbackByID_Call) RunAndReturn(run func(ctx context.Context, feedbackID string) (model.SiteFeedback, error)) *SiteFeedbackRepo_GetSiteFeedbackByID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSiteFeedbackAsRead provides a mock function for the type SiteFeedbackRepo
func (_mock *SiteFeedbackRepo) MarkSiteFeedbackAsRead(ctx context.Context, feedbackID string) error {
	ret := _mock.Called(ctx, feedbackID)

	if len(ret) == 0 {
		panic("no return value specified for MarkSiteFeedbackAsRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, feedbackID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SiteFeedbackRepo_MarkSiteFeedbackAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSiteFeedbackAsRead'
type SiteFeedbackRepo_MarkSiteFeedbackAsRead_Call struct {
	*mock.Call
}

// MarkSiteFeedbackAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - feedbackID string
func (_e *SiteFeedbackRepo_Expecter) MarkSiteFeedbackAsRead(ctx interface{}, feedbackID interface{}) *SiteFeedbackRepo_MarkSiteFeedbackAsRead_Call {
	return &SiteFeedbackRepo_MarkSiteFeedbackAsRead_Call{Call: _e.mock.On("MarkSiteFeedbackAsRead", ctx, feedbackID)}
}

func (_c *SiteFeedbackRepo_MarkSiteFeedbackAsRead_Call) Run(run func(ctx context.Context, feedbackID string)) *SiteFeedbackRepo_MarkSiteFeedbackAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SiteFeedbackRepo_MarkSiteFeedbackAsRead_Call) Return(err error) *SiteFeedbackRepo_MarkSiteFeedbackAsRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SiteFeedbackRepo_MarkSiteFeedbackAsRead_Call) RunAndReturn(run func(ctx context.Context, feedbackID string) error) *SiteFeedbackRepo_MarkSiteFeedbackAsRead_Call {
	_c.Call.Return(run)
	return _c
}
