name: "Install dependencies"
description: "Run pnpm install with node_modules and cache enabled"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/pnpm-setup

    - name: Install dependencies
      shell: bash
      run: pnpm install
