# fly.toml app configuration file generated for ragger-snowy-sound-6162 on 2024-08-30T01:38:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ragger-snowy-sound-6162'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 4444
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
