packages:
  - apps/*
  - packages/*
  - playwright

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
