// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "echo Webkom",
            "email": "webkom@echo.uib.no"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/adapters_http_routes_api.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/happenings": {
            "get": {
                "description": "Retrives a list of all happenings and returns them in a JSON array.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "happenings"
                ],
                "summary": "Get all happenings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/uno_domain_model.Happening"
                            }
                        }
                    }
                }
            }
        },
        "/happenings/{id}": {
            "get": {
                "description": "Retrieves a specific happening by its unique identifier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "happenings"
                ],
                "summary": "Get happening by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Happening ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/uno_domain_model.Happening"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "type"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "type"
                        }
                    }
                }
            }
        },
        "/happenings/{id}/questions": {
            "get": {
                "description": "Retrieves all questions for a specific happening.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "happenings"
                ],
                "summary": "Get happening questions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Happening ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/uno_domain_model.Question"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "type"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "type"
                        }
                    }
                }
            }
        },
        "/happenings/{id}/registrations": {
            "get": {
                "description": "Retrieves all registrations for a specific happening.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "happenings"
                ],
                "summary": "Get happening registrations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Happening ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/uno_domain_model.Registration"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "type"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "type"
                        }
                    }
                }
            }
        },
        "/happenings/{id}/registrations/count": {
            "get": {
                "description": "Retrieves the count of registrations for a specific happening.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "happenings"
                ],
                "summary": "Get happening registrations count",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Happening ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/adapters_http_routes_api.GroupedRegistration"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "type"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "type"
                        }
                    }
                }
            }
        },
        "/happenings/{id}/spot-ranges": {
            "get": {
                "description": "Retrieves all spot ranges for a specific happening.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "happenings"
                ],
                "summary": "Get happening spot ranges",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Happening ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/uno_domain_model.SpotRange"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "type"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "type"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "adapters_http_routes_api.GroupedRegistration": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "integer"
                },
                "registered": {
                    "type": "integer"
                },
                "waiting": {
                    "type": "integer"
                }
            }
        },
        "adapters_http_routes_api.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "uno_domain_model.Happening": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "registrationEnd": {
                    "type": "string"
                },
                "registrationGroups": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "registrationStart": {
                    "type": "string"
                },
                "registrationStartGroups": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "uno_domain_model.Question": {
            "type": "object",
            "properties": {
                "happeningID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isSensitive": {
                    "type": "boolean"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "required": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "uno_domain_model.Registration": {
            "type": "object",
            "properties": {
                "changedAt": {
                    "type": "string"
                },
                "changedBy": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "happeningID": {
                    "type": "string"
                },
                "prevStatus": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/uno_domain_model.RegistrationStatus"
                },
                "unregisterReason": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "uno_domain_model.RegistrationStatus": {
            "type": "string",
            "enum": [
                "registered",
                "waiting",
                "unregistered",
                "pending",
                "removed"
            ],
            "x-enum-varnames": [
                "RegistrationStatusRegistered",
                "RegistrationStatusWaitlisted",
                "RegistrationStatusUnregistered",
                "RegistrationStatusPending",
                "RegistrationStatusRemoved"
            ]
        },
        "uno_domain_model.SpotRange": {
            "type": "object",
            "properties": {
                "happeningID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "maxYear": {
                    "type": "integer"
                },
                "minYear": {
                    "type": "integer"
                },
                "spots": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your bearer token in the format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Uno API",
	Description:      "HTTP REST API for echo Webkom Uno backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
