services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy-data:/data
    networks: [caddy]

  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/deploy/dozzle/users.yaml:/data/users.yaml
    environment:
      DOZZLE_AUTH_PROVIDER: simple
    labels:
      caddy: ${PREVIEW_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks: [caddy]

volumes:
  caddy-data:

networks:
  caddy:
    name: caddy
