/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProfileReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "profile";
};

export type HungerGames = {
  _id: string;
  _type: "hungerGames";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  profile: ProfileReference;
  isDead?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Merch = {
  _id: string;
  _type: "merch";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  price: number;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Markdown;
};

export type Markdown = string;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Ttime = {
  _type: "ttime";
  hour: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23;
  minute: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text: string;
  expiringDate: string;
  backgroundColor?: Color;
  textColor?: Color;
  linkTo?: string;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Movie = {
  _id: string;
  _type: "movie";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  date: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: string;
};

export type Question = {
  _type: "question";
  id: string;
  title: string;
  required: boolean;
  type: "text" | "textarea" | "checkbox" | "radio";
  isSensitive?: boolean;
  options?: Array<string>;
};

export type ContactProfile = {
  _type: "contactProfile";
  profile: ProfileReference;
  email: string;
};

export type SpotRange = {
  _type: "spotRange";
  minYear: number;
  maxYear: number;
  spots: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type MeetingMinute = {
  _id: string;
  _type: "meetingMinute";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  date: string;
  isAllMeeting: boolean;
  document: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type StudentGroup = {
  _id: string;
  _type: "studentGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  groupType: "board" | "subgroup" | "suborg" | "intgroup" | "sport" | "hidden";
  isActive: boolean;
  socials?: {
    email?: string;
    facebook?: string;
    instagram?: string;
    linkedin?: string;
  };
  description?: Markdown;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  members?: Array<{
    profile?: ProfileReference;
    role?: string;
    _type: "member";
    _key: string;
  }>;
};

export type StaticInfo = {
  _id: string;
  _type: "staticInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  pageType: "for-students" | "for-companies" | "about";
  body: Markdown;
};

export type CompanyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "company";
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type Job = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  company: CompanyReference;
  expiresAt: string;
  weight: number;
  locations: Array<{
    _key: string;
  } & LocationReference>;
  jobType: "fulltime" | "parttime" | "internship" | "summerjob" | "event" | "ad";
  link: string;
  deadline?: string;
  degreeYears?: {
    FIRST?: boolean;
    SECOND?: boolean;
    THIRD?: boolean;
    FOURTH?: boolean;
    FIFTH?: boolean;
    PHD?: boolean;
  };
  body: Markdown;
};

export type StudentGroupReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "studentGroup";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  authors?: ArrayOf<StudentGroupReference | ProfileReference>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body: Markdown;
};

export type RepeatingHappening = {
  _id: string;
  _type: "repeatingHappening";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  happeningType: "event" | "external";
  organizers?: Array<{
    _key: string;
  } & StudentGroupReference>;
  location?: LocationReference;
  cost?: number;
  dayOfWeek: 1 | 2 | 3 | 4 | 5 | 6 | 0;
  startTime: Ttime;
  endTime: Ttime;
  startDate: string;
  endDate: string;
  interval: "weekly" | "bi-weekly" | "monthly";
  ignoredDates?: Array<string>;
  contacts?: Array<{
    _key: string;
  } & ContactProfile>;
  externalLink?: string;
  body?: Markdown;
};

export type Happening = {
  _id: string;
  _type: "happening";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  isPinned?: boolean;
  happeningType: "event" | "bedpres" | "external";
  organizers?: Array<{
    _key: string;
  } & StudentGroupReference>;
  company?: CompanyReference;
  location?: LocationReference;
  cost?: number;
  hideRegistrations?: boolean;
  date: string;
  endDate?: string;
  registrationStartGroups?: string;
  registrationGroups?: Array<{
    _key: string;
  } & StudentGroupReference>;
  registrationStart?: string;
  registrationEnd?: string;
  contacts?: Array<{
    _key: string;
  } & ContactProfile>;
  spotRanges?: Array<{
    _key: string;
  } & SpotRange>;
  additionalQuestions?: Array<{
    _key: string;
  } & Question>;
  externalLink?: string;
  body?: Markdown;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  link?: string;
};

export type Company = {
  _id: string;
  _type: "company";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  website: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type HsApplication = {
  _id: string;
  _type: "hs-application";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  profile: ProfileReference;
  poster: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  picture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socials?: {
    email?: string;
    linkedin?: string;
  };
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ProfileReference | HungerGames | SanityImageAssetReference | Merch | Markdown | SanityImageCrop | SanityImageHotspot | Slug | Ttime | Banner | Color | Movie | Question | ContactProfile | SpotRange | SanityFileAssetReference | MeetingMinute | StudentGroup | StaticInfo | CompanyReference | LocationReference | Job | StudentGroupReference | Post | RepeatingHappening | Happening | Location | Company | HsApplication | Profile | RgbaColor | HsvaColor | HslaColor | MediaTag | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<T & {
  _key: string;
}>;

// Source: ../../packages/seeder/src/sanity/query.ts
// Variable: happeningQueryList
// Query: *[_type == "happening" && !(_id in path('drafts.**'))] {  _id,  title,  "slug": slug.current,  "date": date,  happeningType,  "registrationStartGroups": registrationStartGroups,  "registrationGroups": registrationGroups[]->slug.current,  "registrationStart": registrationStart,  "registrationEnd": registrationEnd,  "groups": organizers[]->slug.current,  "spotRanges": spotRanges[] {    spots,    minYear,    maxYear,  },  "questions": additionalQuestions[] {    id,    title,    required,    type,    isSensitive,    options,  }}
export type HappeningQueryListResult = Array<{
  _id: string;
  title: string;
  slug: string;
  date: string;
  happeningType: "bedpres" | "event" | "external";
  registrationStartGroups: string | null;
  registrationGroups: Array<string> | null;
  registrationStart: string | null;
  registrationEnd: string | null;
  groups: Array<string> | null;
  spotRanges: Array<{
    spots: number;
    minYear: number;
    maxYear: number;
  }> | null;
  questions: Array<{
    id: string;
    title: string;
    required: boolean;
    type: "checkbox" | "radio" | "text" | "textarea";
    isSensitive: boolean | null;
    options: Array<string> | null;
  }> | null;
}>;

