import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="m-0 p-0">
      <body className="m-0 p-0">{children}</body>
    </html>
  );
}
