services:
  db:
    image: postgres:15.7
    restart: always
    container_name: echo-web-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: echo-web
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  kv:
    image: redis/redis-stack:edge
    restart: unless-stopped
    container_name: echo-web-kv
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data

volumes:
  db:
    driver: local
  kv:
    driver: local
