version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: echo-web-db
    environment:
      MYSQL_DATABASE: "new-echo-web-database"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
