services:
  db:
    image: postgres:15.7
    restart: always
    container_name: echo-web-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: echo-web
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  db:
    driver: local
