// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewBanInfoRepo creates a new instance of BanInfoRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBanInfoRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BanInfoRepo {
	mock := &BanInfoRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BanInfoRepo is an autogenerated mock type for the BanInfoRepo type
type BanInfoRepo struct {
	mock.Mock
}

type BanInfoRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *BanInfoRepo) EXPECT() *BanInfoRepo_Expecter {
	return &BanInfoRepo_Expecter{mock: &_m.Mock}
}

// CreateBan provides a mock function for the type BanInfoRepo
func (_mock *BanInfoRepo) CreateBan(ctx context.Context, ban model.NewBanInfo) (model.ModBanInfo, error) {
	ret := _mock.Called(ctx, ban)

	if len(ret) == 0 {
		panic("no return value specified for CreateBan")
	}

	var r0 model.ModBanInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.NewBanInfo) (model.ModBanInfo, error)); ok {
		return returnFunc(ctx, ban)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.NewBanInfo) model.ModBanInfo); ok {
		r0 = returnFunc(ctx, ban)
	} else {
		r0 = ret.Get(0).(model.ModBanInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.NewBanInfo) error); ok {
		r1 = returnFunc(ctx, ban)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BanInfoRepo_CreateBan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBan'
type BanInfoRepo_CreateBan_Call struct {
	*mock.Call
}

// CreateBan is a helper method to define mock.On call
//   - ctx context.Context
//   - ban model.NewBanInfo
func (_e *BanInfoRepo_Expecter) CreateBan(ctx interface{}, ban interface{}) *BanInfoRepo_CreateBan_Call {
	return &BanInfoRepo_CreateBan_Call{Call: _e.mock.On("CreateBan", ctx, ban)}
}

func (_c *BanInfoRepo_CreateBan_Call) Run(run func(ctx context.Context, ban model.NewBanInfo)) *BanInfoRepo_CreateBan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.NewBanInfo
		if args[1] != nil {
			arg1 = args[1].(model.NewBanInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BanInfoRepo_CreateBan_Call) Return(modBanInfo model.ModBanInfo, err error) *BanInfoRepo_CreateBan_Call {
	_c.Call.Return(modBanInfo, err)
	return _c
}

func (_c *BanInfoRepo_CreateBan_Call) RunAndReturn(run func(ctx context.Context, ban model.NewBanInfo) (model.ModBanInfo, error)) *BanInfoRepo_CreateBan_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function for the type BanInfoRepo
func (_mock *BanInfoRepo) DeleteExpired(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BanInfoRepo_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type BanInfoRepo_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BanInfoRepo_Expecter) DeleteExpired(ctx interface{}) *BanInfoRepo_DeleteExpired_Call {
	return &BanInfoRepo_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *BanInfoRepo_DeleteExpired_Call) Run(run func(ctx context.Context)) *BanInfoRepo_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BanInfoRepo_DeleteExpired_Call) Return(err error) *BanInfoRepo_DeleteExpired_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BanInfoRepo_DeleteExpired_Call) RunAndReturn(run func(ctx context.Context) error) *BanInfoRepo_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// GetBanInfoByUserID provides a mock function for the type BanInfoRepo
func (_mock *BanInfoRepo) GetBanInfoByUserID(ctx context.Context, userID string) (*model.ModBanInfo, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBanInfoByUserID")
	}

	var r0 *model.ModBanInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ModBanInfo, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ModBanInfo); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ModBanInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BanInfoRepo_GetBanInfoByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBanInfoByUserID'
type BanInfoRepo_GetBanInfoByUserID_Call struct {
	*mock.Call
}

// GetBanInfoByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *BanInfoRepo_Expecter) GetBanInfoByUserID(ctx interface{}, userID interface{}) *BanInfoRepo_GetBanInfoByUserID_Call {
	return &BanInfoRepo_GetBanInfoByUserID_Call{Call: _e.mock.On("GetBanInfoByUserID", ctx, userID)}
}

func (_c *BanInfoRepo_GetBanInfoByUserID_Call) Run(run func(ctx context.Context, userID string)) *BanInfoRepo_GetBanInfoByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BanInfoRepo_GetBanInfoByUserID_Call) Return(modBanInfo *model.ModBanInfo, err error) *BanInfoRepo_GetBanInfoByUserID_Call {
	_c.Call.Return(modBanInfo, err)
	return _c
}

func (_c *BanInfoRepo_GetBanInfoByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*model.ModBanInfo, error)) *BanInfoRepo_GetBanInfoByUserID_Call {
	_c.Call.Return(run)
	return _c
}
