// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache[T] {
	mock := &Cache[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cache is an autogenerated mock type for the Cache type
type Cache[T any] struct {
	mock.Mock
}

type Cache_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Cache[T]) EXPECT() *Cache_Expecter[T] {
	return &Cache_Expecter[T]{mock: &_m.Mock}
}

// Delete provides a mock function for the type Cache
func (_mock *Cache[T]) Delete(key string) {
	_mock.Called(key)
	return
}

// Cache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Cache_Delete_Call[T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *Cache_Expecter[T]) Delete(key interface{}) *Cache_Delete_Call[T] {
	return &Cache_Delete_Call[T]{Call: _e.mock.On("Delete", key)}
}

func (_c *Cache_Delete_Call[T]) Run(run func(key string)) *Cache_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Cache_Delete_Call[T]) Return() *Cache_Delete_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *Cache_Delete_Call[T]) RunAndReturn(run func(key string)) *Cache_Delete_Call[T] {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type Cache
func (_mock *Cache[T]) Get(key string) (T, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 T
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (T, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) T); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Cache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Cache_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *Cache_Expecter[T]) Get(key interface{}) *Cache_Get_Call[T] {
	return &Cache_Get_Call[T]{Call: _e.mock.On("Get", key)}
}

func (_c *Cache_Get_Call[T]) Run(run func(key string)) *Cache_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Cache_Get_Call[T]) Return(v T, b bool) *Cache_Get_Call[T] {
	_c.Call.Return(v, b)
	return _c
}

func (_c *Cache_Get_Call[T]) RunAndReturn(run func(key string) (T, bool)) *Cache_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type Cache
func (_mock *Cache[T]) Set(key string, value T, ttl time.Duration) {
	_mock.Called(key, value, ttl)
	return
}

// Cache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Cache_Set_Call[T any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value T
//   - ttl time.Duration
func (_e *Cache_Expecter[T]) Set(key interface{}, value interface{}, ttl interface{}) *Cache_Set_Call[T] {
	return &Cache_Set_Call[T]{Call: _e.mock.On("Set", key, value, ttl)}
}

func (_c *Cache_Set_Call[T]) Run(run func(key string, value T, ttl time.Duration)) *Cache_Set_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cache_Set_Call[T]) Return() *Cache_Set_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *Cache_Set_Call[T]) RunAndReturn(run func(key string, value T, ttl time.Duration)) *Cache_Set_Call[T] {
	_c.Run(run)
	return _c
}
