// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCMSBannerRepo creates a new instance of CMSBannerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCMSBannerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CMSBannerRepo {
	mock := &CMSBannerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CMSBannerRepo is an autogenerated mock type for the CMSBannerRepo type
type CMSBannerRepo struct {
	mock.Mock
}

type CMSBannerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CMSBannerRepo) EXPECT() *CMSBannerRepo_Expecter {
	return &CMSBannerRepo_Expecter{mock: &_m.Mock}
}

// GetBanner provides a mock function for the type CMSBannerRepo
func (_mock *CMSBannerRepo) GetBanner(ctx context.Context) (*model.CMSBanner, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBanner")
	}

	var r0 *model.CMSBanner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.CMSBanner, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.CMSBanner); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CMSBanner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CMSBannerRepo_GetBanner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBanner'
type CMSBannerRepo_GetBanner_Call struct {
	*mock.Call
}

// GetBanner is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CMSBannerRepo_Expecter) GetBanner(ctx interface{}) *CMSBannerRepo_GetBanner_Call {
	return &CMSBannerRepo_GetBanner_Call{Call: _e.mock.On("GetBanner", ctx)}
}

func (_c *CMSBannerRepo_GetBanner_Call) Run(run func(ctx context.Context)) *CMSBannerRepo_GetBanner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CMSBannerRepo_GetBanner_Call) Return(cMSBanner *model.CMSBanner, err error) *CMSBannerRepo_GetBanner_Call {
	_c.Call.Return(cMSBanner, err)
	return _c
}

func (_c *CMSBannerRepo_GetBanner_Call) RunAndReturn(run func(ctx context.Context) (*model.CMSBanner, error)) *CMSBannerRepo_GetBanner_Call {
	_c.Call.Return(run)
	return _c
}
