// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCMSMeetingMinuteRepo creates a new instance of CMSMeetingMinuteRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCMSMeetingMinuteRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CMSMeetingMinuteRepo {
	mock := &CMSMeetingMinuteRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CMSMeetingMinuteRepo is an autogenerated mock type for the CMSMeetingMinuteRepo type
type CMSMeetingMinuteRepo struct {
	mock.Mock
}

type CMSMeetingMinuteRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CMSMeetingMinuteRepo) EXPECT() *CMSMeetingMinuteRepo_Expecter {
	return &CMSMeetingMinuteRepo_Expecter{mock: &_m.Mock}
}

// GetAllMeetingMinutes provides a mock function for the type CMSMeetingMinuteRepo
func (_mock *CMSMeetingMinuteRepo) GetAllMeetingMinutes(ctx context.Context) ([]model.CMSMeetingMinute, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMeetingMinutes")
	}

	var r0 []model.CMSMeetingMinute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.CMSMeetingMinute, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.CMSMeetingMinute); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CMSMeetingMinute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CMSMeetingMinuteRepo_GetAllMeetingMinutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMeetingMinutes'
type CMSMeetingMinuteRepo_GetAllMeetingMinutes_Call struct {
	*mock.Call
}

// GetAllMeetingMinutes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CMSMeetingMinuteRepo_Expecter) GetAllMeetingMinutes(ctx interface{}) *CMSMeetingMinuteRepo_GetAllMeetingMinutes_Call {
	return &CMSMeetingMinuteRepo_GetAllMeetingMinutes_Call{Call: _e.mock.On("GetAllMeetingMinutes", ctx)}
}

func (_c *CMSMeetingMinuteRepo_GetAllMeetingMinutes_Call) Run(run func(ctx context.Context)) *CMSMeetingMinuteRepo_GetAllMeetingMinutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CMSMeetingMinuteRepo_GetAllMeetingMinutes_Call) Return(cMSMeetingMinutes []model.CMSMeetingMinute, err error) *CMSMeetingMinuteRepo_GetAllMeetingMinutes_Call {
	_c.Call.Return(cMSMeetingMinutes, err)
	return _c
}

func (_c *CMSMeetingMinuteRepo_GetAllMeetingMinutes_Call) RunAndReturn(run func(ctx context.Context) ([]model.CMSMeetingMinute, error)) *CMSMeetingMinuteRepo_GetAllMeetingMinutes_Call {
	_c.Call.Return(run)
	return _c
}
