// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCMSPostRepo creates a new instance of CMSPostRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCMSPostRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CMSPostRepo {
	mock := &CMSPostRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CMSPostRepo is an autogenerated mock type for the CMSPostRepo type
type CMSPostRepo struct {
	mock.Mock
}

type CMSPostRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CMSPostRepo) EXPECT() *CMSPostRepo_Expecter {
	return &CMSPostRepo_Expecter{mock: &_m.Mock}
}

// GetAllPosts provides a mock function for the type CMSPostRepo
func (_mock *CMSPostRepo) GetAllPosts(ctx context.Context) ([]model.CMSPost, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPosts")
	}

	var r0 []model.CMSPost
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.CMSPost, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.CMSPost); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CMSPost)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CMSPostRepo_GetAllPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPosts'
type CMSPostRepo_GetAllPosts_Call struct {
	*mock.Call
}

// GetAllPosts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CMSPostRepo_Expecter) GetAllPosts(ctx interface{}) *CMSPostRepo_GetAllPosts_Call {
	return &CMSPostRepo_GetAllPosts_Call{Call: _e.mock.On("GetAllPosts", ctx)}
}

func (_c *CMSPostRepo_GetAllPosts_Call) Run(run func(ctx context.Context)) *CMSPostRepo_GetAllPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CMSPostRepo_GetAllPosts_Call) Return(cMSPosts []model.CMSPost, err error) *CMSPostRepo_GetAllPosts_Call {
	_c.Call.Return(cMSPosts, err)
	return _c
}

func (_c *CMSPostRepo_GetAllPosts_Call) RunAndReturn(run func(ctx context.Context) ([]model.CMSPost, error)) *CMSPostRepo_GetAllPosts_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostBySlug provides a mock function for the type CMSPostRepo
func (_mock *CMSPostRepo) GetPostBySlug(ctx context.Context, slug string) (*model.CMSPost, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetPostBySlug")
	}

	var r0 *model.CMSPost
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.CMSPost, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.CMSPost); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CMSPost)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CMSPostRepo_GetPostBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostBySlug'
type CMSPostRepo_GetPostBySlug_Call struct {
	*mock.Call
}

// GetPostBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *CMSPostRepo_Expecter) GetPostBySlug(ctx interface{}, slug interface{}) *CMSPostRepo_GetPostBySlug_Call {
	return &CMSPostRepo_GetPostBySlug_Call{Call: _e.mock.On("GetPostBySlug", ctx, slug)}
}

func (_c *CMSPostRepo_GetPostBySlug_Call) Run(run func(ctx context.Context, slug string)) *CMSPostRepo_GetPostBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CMSPostRepo_GetPostBySlug_Call) Return(cMSPost *model.CMSPost, err error) *CMSPostRepo_GetPostBySlug_Call {
	_c.Call.Return(cMSPost, err)
	return _c
}

func (_c *CMSPostRepo_GetPostBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*model.CMSPost, error)) *CMSPostRepo_GetPostBySlug_Call {
	_c.Call.Return(run)
	return _c
}
