// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCMSStudentGroupRepo creates a new instance of CMSStudentGroupRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCMSStudentGroupRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CMSStudentGroupRepo {
	mock := &CMSStudentGroupRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CMSStudentGroupRepo is an autogenerated mock type for the CMSStudentGroupRepo type
type CMSStudentGroupRepo struct {
	mock.Mock
}

type CMSStudentGroupRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CMSStudentGroupRepo) EXPECT() *CMSStudentGroupRepo_Expecter {
	return &CMSStudentGroupRepo_Expecter{mock: &_m.Mock}
}

// GetStudentGroupBySlug provides a mock function for the type CMSStudentGroupRepo
func (_mock *CMSStudentGroupRepo) GetStudentGroupBySlug(ctx context.Context, slug string) (*model.CMSStudentGroup, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentGroupBySlug")
	}

	var r0 *model.CMSStudentGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.CMSStudentGroup, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.CMSStudentGroup); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CMSStudentGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CMSStudentGroupRepo_GetStudentGroupBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudentGroupBySlug'
type CMSStudentGroupRepo_GetStudentGroupBySlug_Call struct {
	*mock.Call
}

// GetStudentGroupBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *CMSStudentGroupRepo_Expecter) GetStudentGroupBySlug(ctx interface{}, slug interface{}) *CMSStudentGroupRepo_GetStudentGroupBySlug_Call {
	return &CMSStudentGroupRepo_GetStudentGroupBySlug_Call{Call: _e.mock.On("GetStudentGroupBySlug", ctx, slug)}
}

func (_c *CMSStudentGroupRepo_GetStudentGroupBySlug_Call) Run(run func(ctx context.Context, slug string)) *CMSStudentGroupRepo_GetStudentGroupBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CMSStudentGroupRepo_GetStudentGroupBySlug_Call) Return(cMSStudentGroup *model.CMSStudentGroup, err error) *CMSStudentGroupRepo_GetStudentGroupBySlug_Call {
	_c.Call.Return(cMSStudentGroup, err)
	return _c
}

func (_c *CMSStudentGroupRepo_GetStudentGroupBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*model.CMSStudentGroup, error)) *CMSStudentGroupRepo_GetStudentGroupBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetStudentGroupsByType provides a mock function for the type CMSStudentGroupRepo
func (_mock *CMSStudentGroupRepo) GetStudentGroupsByType(ctx context.Context, groupType string, n int) ([]model.CMSStudentGroup, error) {
	ret := _mock.Called(ctx, groupType, n)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentGroupsByType")
	}

	var r0 []model.CMSStudentGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]model.CMSStudentGroup, error)); ok {
		return returnFunc(ctx, groupType, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []model.CMSStudentGroup); ok {
		r0 = returnFunc(ctx, groupType, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CMSStudentGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, groupType, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CMSStudentGroupRepo_GetStudentGroupsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudentGroupsByType'
type CMSStudentGroupRepo_GetStudentGroupsByType_Call struct {
	*mock.Call
}

// GetStudentGroupsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - groupType string
//   - n int
func (_e *CMSStudentGroupRepo_Expecter) GetStudentGroupsByType(ctx interface{}, groupType interface{}, n interface{}) *CMSStudentGroupRepo_GetStudentGroupsByType_Call {
	return &CMSStudentGroupRepo_GetStudentGroupsByType_Call{Call: _e.mock.On("GetStudentGroupsByType", ctx, groupType, n)}
}

func (_c *CMSStudentGroupRepo_GetStudentGroupsByType_Call) Run(run func(ctx context.Context, groupType string, n int)) *CMSStudentGroupRepo_GetStudentGroupsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CMSStudentGroupRepo_GetStudentGroupsByType_Call) Return(cMSStudentGroups []model.CMSStudentGroup, err error) *CMSStudentGroupRepo_GetStudentGroupsByType_Call {
	_c.Call.Return(cMSStudentGroups, err)
	return _c
}

func (_c *CMSStudentGroupRepo_GetStudentGroupsByType_Call) RunAndReturn(run func(ctx context.Context, groupType string, n int) ([]model.CMSStudentGroup, error)) *CMSStudentGroupRepo_GetStudentGroupsByType_Call {
	_c.Call.Return(run)
	return _c
}
