// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCMSStaticInfoRepo creates a new instance of CMSStaticInfoRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCMSStaticInfoRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CMSStaticInfoRepo {
	mock := &CMSStaticInfoRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CMSStaticInfoRepo is an autogenerated mock type for the CMSStaticInfoRepo type
type CMSStaticInfoRepo struct {
	mock.Mock
}

type CMSStaticInfoRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CMSStaticInfoRepo) EXPECT() *CMSStaticInfoRepo_Expecter {
	return &CMSStaticInfoRepo_Expecter{mock: &_m.Mock}
}

// GetAllStaticInfo provides a mock function for the type CMSStaticInfoRepo
func (_mock *CMSStaticInfoRepo) GetAllStaticInfo(ctx context.Context) ([]model.CMSStaticInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllStaticInfo")
	}

	var r0 []model.CMSStaticInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.CMSStaticInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.CMSStaticInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CMSStaticInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CMSStaticInfoRepo_GetAllStaticInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStaticInfo'
type CMSStaticInfoRepo_GetAllStaticInfo_Call struct {
	*mock.Call
}

// GetAllStaticInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CMSStaticInfoRepo_Expecter) GetAllStaticInfo(ctx interface{}) *CMSStaticInfoRepo_GetAllStaticInfo_Call {
	return &CMSStaticInfoRepo_GetAllStaticInfo_Call{Call: _e.mock.On("GetAllStaticInfo", ctx)}
}

func (_c *CMSStaticInfoRepo_GetAllStaticInfo_Call) Run(run func(ctx context.Context)) *CMSStaticInfoRepo_GetAllStaticInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CMSStaticInfoRepo_GetAllStaticInfo_Call) Return(cMSStaticInfos []model.CMSStaticInfo, err error) *CMSStaticInfoRepo_GetAllStaticInfo_Call {
	_c.Call.Return(cMSStaticInfos, err)
	return _c
}

func (_c *CMSStaticInfoRepo_GetAllStaticInfo_Call) RunAndReturn(run func(ctx context.Context) ([]model.CMSStaticInfo, error)) *CMSStaticInfoRepo_GetAllStaticInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaticInfoBySlug provides a mock function for the type CMSStaticInfoRepo
func (_mock *CMSStaticInfoRepo) GetStaticInfoBySlug(ctx context.Context, pageType string, slug string) (*model.CMSStaticInfo, error) {
	ret := _mock.Called(ctx, pageType, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetStaticInfoBySlug")
	}

	var r0 *model.CMSStaticInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.CMSStaticInfo, error)); ok {
		return returnFunc(ctx, pageType, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.CMSStaticInfo); ok {
		r0 = returnFunc(ctx, pageType, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CMSStaticInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, pageType, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CMSStaticInfoRepo_GetStaticInfoBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaticInfoBySlug'
type CMSStaticInfoRepo_GetStaticInfoBySlug_Call struct {
	*mock.Call
}

// GetStaticInfoBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - pageType string
//   - slug string
func (_e *CMSStaticInfoRepo_Expecter) GetStaticInfoBySlug(ctx interface{}, pageType interface{}, slug interface{}) *CMSStaticInfoRepo_GetStaticInfoBySlug_Call {
	return &CMSStaticInfoRepo_GetStaticInfoBySlug_Call{Call: _e.mock.On("GetStaticInfoBySlug", ctx, pageType, slug)}
}

func (_c *CMSStaticInfoRepo_GetStaticInfoBySlug_Call) Run(run func(ctx context.Context, pageType string, slug string)) *CMSStaticInfoRepo_GetStaticInfoBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CMSStaticInfoRepo_GetStaticInfoBySlug_Call) Return(cMSStaticInfo *model.CMSStaticInfo, err error) *CMSStaticInfoRepo_GetStaticInfoBySlug_Call {
	_c.Call.Return(cMSStaticInfo, err)
	return _c
}

func (_c *CMSStaticInfoRepo_GetStaticInfoBySlug_Call) RunAndReturn(run func(ctx context.Context, pageType string, slug string) (*model.CMSStaticInfo, error)) *CMSStaticInfoRepo_GetStaticInfoBySlug_Call {
	_c.Call.Return(run)
	return _c
}
