// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewDegreeRepo creates a new instance of DegreeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDegreeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DegreeRepo {
	mock := &DegreeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DegreeRepo is an autogenerated mock type for the DegreeRepo type
type DegreeRepo struct {
	mock.Mock
}

type DegreeRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *DegreeRepo) EXPECT() *DegreeRepo_Expecter {
	return &DegreeRepo_Expecter{mock: &_m.Mock}
}

// CreateDegree provides a mock function for the type DegreeRepo
func (_mock *DegreeRepo) CreateDegree(ctx context.Context, degree model.Degree) (model.Degree, error) {
	ret := _mock.Called(ctx, degree)

	if len(ret) == 0 {
		panic("no return value specified for CreateDegree")
	}

	var r0 model.Degree
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Degree) (model.Degree, error)); ok {
		return returnFunc(ctx, degree)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Degree) model.Degree); ok {
		r0 = returnFunc(ctx, degree)
	} else {
		r0 = ret.Get(0).(model.Degree)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Degree) error); ok {
		r1 = returnFunc(ctx, degree)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DegreeRepo_CreateDegree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDegree'
type DegreeRepo_CreateDegree_Call struct {
	*mock.Call
}

// CreateDegree is a helper method to define mock.On call
//   - ctx context.Context
//   - degree model.Degree
func (_e *DegreeRepo_Expecter) CreateDegree(ctx interface{}, degree interface{}) *DegreeRepo_CreateDegree_Call {
	return &DegreeRepo_CreateDegree_Call{Call: _e.mock.On("CreateDegree", ctx, degree)}
}

func (_c *DegreeRepo_CreateDegree_Call) Run(run func(ctx context.Context, degree model.Degree)) *DegreeRepo_CreateDegree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Degree
		if args[1] != nil {
			arg1 = args[1].(model.Degree)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DegreeRepo_CreateDegree_Call) Return(degree1 model.Degree, err error) *DegreeRepo_CreateDegree_Call {
	_c.Call.Return(degree1, err)
	return _c
}

func (_c *DegreeRepo_CreateDegree_Call) RunAndReturn(run func(ctx context.Context, degree model.Degree) (model.Degree, error)) *DegreeRepo_CreateDegree_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDegree provides a mock function for the type DegreeRepo
func (_mock *DegreeRepo) DeleteDegree(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDegree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DegreeRepo_DeleteDegree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDegree'
type DegreeRepo_DeleteDegree_Call struct {
	*mock.Call
}

// DeleteDegree is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *DegreeRepo_Expecter) DeleteDegree(ctx interface{}, id interface{}) *DegreeRepo_DeleteDegree_Call {
	return &DegreeRepo_DeleteDegree_Call{Call: _e.mock.On("DeleteDegree", ctx, id)}
}

func (_c *DegreeRepo_DeleteDegree_Call) Run(run func(ctx context.Context, id string)) *DegreeRepo_DeleteDegree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DegreeRepo_DeleteDegree_Call) Return(err error) *DegreeRepo_DeleteDegree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DegreeRepo_DeleteDegree_Call) RunAndReturn(run func(ctx context.Context, id string) error) *DegreeRepo_DeleteDegree_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDegrees provides a mock function for the type DegreeRepo
func (_mock *DegreeRepo) GetAllDegrees(ctx context.Context) ([]model.Degree, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDegrees")
	}

	var r0 []model.Degree
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Degree, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Degree); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Degree)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DegreeRepo_GetAllDegrees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDegrees'
type DegreeRepo_GetAllDegrees_Call struct {
	*mock.Call
}

// GetAllDegrees is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DegreeRepo_Expecter) GetAllDegrees(ctx interface{}) *DegreeRepo_GetAllDegrees_Call {
	return &DegreeRepo_GetAllDegrees_Call{Call: _e.mock.On("GetAllDegrees", ctx)}
}

func (_c *DegreeRepo_GetAllDegrees_Call) Run(run func(ctx context.Context)) *DegreeRepo_GetAllDegrees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DegreeRepo_GetAllDegrees_Call) Return(degrees []model.Degree, err error) *DegreeRepo_GetAllDegrees_Call {
	_c.Call.Return(degrees, err)
	return _c
}

func (_c *DegreeRepo_GetAllDegrees_Call) RunAndReturn(run func(ctx context.Context) ([]model.Degree, error)) *DegreeRepo_GetAllDegrees_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDegree provides a mock function for the type DegreeRepo
func (_mock *DegreeRepo) UpdateDegree(ctx context.Context, degree model.Degree) (model.Degree, error) {
	ret := _mock.Called(ctx, degree)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDegree")
	}

	var r0 model.Degree
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Degree) (model.Degree, error)); ok {
		return returnFunc(ctx, degree)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Degree) model.Degree); ok {
		r0 = returnFunc(ctx, degree)
	} else {
		r0 = ret.Get(0).(model.Degree)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Degree) error); ok {
		r1 = returnFunc(ctx, degree)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DegreeRepo_UpdateDegree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDegree'
type DegreeRepo_UpdateDegree_Call struct {
	*mock.Call
}

// UpdateDegree is a helper method to define mock.On call
//   - ctx context.Context
//   - degree model.Degree
func (_e *DegreeRepo_Expecter) UpdateDegree(ctx interface{}, degree interface{}) *DegreeRepo_UpdateDegree_Call {
	return &DegreeRepo_UpdateDegree_Call{Call: _e.mock.On("UpdateDegree", ctx, degree)}
}

func (_c *DegreeRepo_UpdateDegree_Call) Run(run func(ctx context.Context, degree model.Degree)) *DegreeRepo_UpdateDegree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Degree
		if args[1] != nil {
			arg1 = args[1].(model.Degree)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DegreeRepo_UpdateDegree_Call) Return(degree1 model.Degree, err error) *DegreeRepo_UpdateDegree_Call {
	_c.Call.Return(degree1, err)
	return _c
}

func (_c *DegreeRepo_UpdateDegree_Call) RunAndReturn(run func(ctx context.Context, degree model.Degree) (model.Degree, error)) *DegreeRepo_UpdateDegree_Call {
	_c.Call.Return(run)
	return _c
}
