// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewDotRepo creates a new instance of DotRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDotRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DotRepo {
	mock := &DotRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DotRepo is an autogenerated mock type for the DotRepo type
type DotRepo struct {
	mock.Mock
}

type DotRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *DotRepo) EXPECT() *DotRepo_Expecter {
	return &DotRepo_Expecter{mock: &_m.Mock}
}

// CleanupOldStrikes provides a mock function for the type DotRepo
func (_mock *DotRepo) CleanupOldStrikes(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOldStrikes")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DotRepo_CleanupOldStrikes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupOldStrikes'
type DotRepo_CleanupOldStrikes_Call struct {
	*mock.Call
}

// CleanupOldStrikes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DotRepo_Expecter) CleanupOldStrikes(ctx interface{}) *DotRepo_CleanupOldStrikes_Call {
	return &DotRepo_CleanupOldStrikes_Call{Call: _e.mock.On("CleanupOldStrikes", ctx)}
}

func (_c *DotRepo_CleanupOldStrikes_Call) Run(run func(ctx context.Context)) *DotRepo_CleanupOldStrikes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DotRepo_CleanupOldStrikes_Call) Return(n int64, err error) *DotRepo_CleanupOldStrikes_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *DotRepo_CleanupOldStrikes_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *DotRepo_CleanupOldStrikes_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDot provides a mock function for the type DotRepo
func (_mock *DotRepo) CreateDot(ctx context.Context, dot model.NewDot) (model.Dot, error) {
	ret := _mock.Called(ctx, dot)

	if len(ret) == 0 {
		panic("no return value specified for CreateDot")
	}

	var r0 model.Dot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.NewDot) (model.Dot, error)); ok {
		return returnFunc(ctx, dot)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.NewDot) model.Dot); ok {
		r0 = returnFunc(ctx, dot)
	} else {
		r0 = ret.Get(0).(model.Dot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.NewDot) error); ok {
		r1 = returnFunc(ctx, dot)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DotRepo_CreateDot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDot'
type DotRepo_CreateDot_Call struct {
	*mock.Call
}

// CreateDot is a helper method to define mock.On call
//   - ctx context.Context
//   - dot model.NewDot
func (_e *DotRepo_Expecter) CreateDot(ctx interface{}, dot interface{}) *DotRepo_CreateDot_Call {
	return &DotRepo_CreateDot_Call{Call: _e.mock.On("CreateDot", ctx, dot)}
}

func (_c *DotRepo_CreateDot_Call) Run(run func(ctx context.Context, dot model.NewDot)) *DotRepo_CreateDot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.NewDot
		if args[1] != nil {
			arg1 = args[1].(model.NewDot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DotRepo_CreateDot_Call) Return(dot1 model.Dot, err error) *DotRepo_CreateDot_Call {
	_c.Call.Return(dot1, err)
	return _c
}

func (_c *DotRepo_CreateDot_Call) RunAndReturn(run func(ctx context.Context, dot model.NewDot) (model.Dot, error)) *DotRepo_CreateDot_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function for the type DotRepo
func (_mock *DotRepo) DeleteExpired(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DotRepo_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type DotRepo_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DotRepo_Expecter) DeleteExpired(ctx interface{}) *DotRepo_DeleteExpired_Call {
	return &DotRepo_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *DotRepo_DeleteExpired_Call) Run(run func(ctx context.Context)) *DotRepo_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DotRepo_DeleteExpired_Call) Return(err error) *DotRepo_DeleteExpired_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DotRepo_DeleteExpired_Call) RunAndReturn(run func(ctx context.Context) error) *DotRepo_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}
