// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewEmailClient creates a new instance of EmailClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailClient {
	mock := &EmailClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmailClient is an autogenerated mock type for the EmailClient type
type EmailClient struct {
	mock.Mock
}

type EmailClient_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailClient) EXPECT() *EmailClient_Expecter {
	return &EmailClient_Expecter{mock: &_m.Mock}
}

// SendAccessDenied provides a mock function for the type EmailClient
func (_mock *EmailClient) SendAccessDenied(ctx context.Context, to []string, subject string, reason string) error {
	ret := _mock.Called(ctx, to, subject, reason)

	if len(ret) == 0 {
		panic("no return value specified for SendAccessDenied")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string) error); ok {
		r0 = returnFunc(ctx, to, subject, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailClient_SendAccessDenied_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAccessDenied'
type EmailClient_SendAccessDenied_Call struct {
	*mock.Call
}

// SendAccessDenied is a helper method to define mock.On call
//   - ctx context.Context
//   - to []string
//   - subject string
//   - reason string
func (_e *EmailClient_Expecter) SendAccessDenied(ctx interface{}, to interface{}, subject interface{}, reason interface{}) *EmailClient_SendAccessDenied_Call {
	return &EmailClient_SendAccessDenied_Call{Call: _e.mock.On("SendAccessDenied", ctx, to, subject, reason)}
}

func (_c *EmailClient_SendAccessDenied_Call) Run(run func(ctx context.Context, to []string, subject string, reason string)) *EmailClient_SendAccessDenied_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EmailClient_SendAccessDenied_Call) Return(err error) *EmailClient_SendAccessDenied_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailClient_SendAccessDenied_Call) RunAndReturn(run func(ctx context.Context, to []string, subject string, reason string) error) *EmailClient_SendAccessDenied_Call {
	_c.Call.Return(run)
	return _c
}

// SendAccessGranted provides a mock function for the type EmailClient
func (_mock *EmailClient) SendAccessGranted(ctx context.Context, to []string, subject string) error {
	ret := _mock.Called(ctx, to, subject)

	if len(ret) == 0 {
		panic("no return value specified for SendAccessGranted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string) error); ok {
		r0 = returnFunc(ctx, to, subject)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailClient_SendAccessGranted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAccessGranted'
type EmailClient_SendAccessGranted_Call struct {
	*mock.Call
}

// SendAccessGranted is a helper method to define mock.On call
//   - ctx context.Context
//   - to []string
//   - subject string
func (_e *EmailClient_Expecter) SendAccessGranted(ctx interface{}, to interface{}, subject interface{}) *EmailClient_SendAccessGranted_Call {
	return &EmailClient_SendAccessGranted_Call{Call: _e.mock.On("SendAccessGranted", ctx, to, subject)}
}

func (_c *EmailClient_SendAccessGranted_Call) Run(run func(ctx context.Context, to []string, subject string)) *EmailClient_SendAccessGranted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmailClient_SendAccessGranted_Call) Return(err error) *EmailClient_SendAccessGranted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailClient_SendAccessGranted_Call) RunAndReturn(run func(ctx context.Context, to []string, subject string) error) *EmailClient_SendAccessGranted_Call {
	_c.Call.Return(run)
	return _c
}

// SendAccessRequestNotification provides a mock function for the type EmailClient
func (_mock *EmailClient) SendAccessRequestNotification(ctx context.Context, to []string, subject string, email string, reason string) error {
	ret := _mock.Called(ctx, to, subject, email, reason)

	if len(ret) == 0 {
		panic("no return value specified for SendAccessRequestNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, subject, email, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailClient_SendAccessRequestNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAccessRequestNotification'
type EmailClient_SendAccessRequestNotification_Call struct {
	*mock.Call
}

// SendAccessRequestNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - to []string
//   - subject string
//   - email string
//   - reason string
func (_e *EmailClient_Expecter) SendAccessRequestNotification(ctx interface{}, to interface{}, subject interface{}, email interface{}, reason interface{}) *EmailClient_SendAccessRequestNotification_Call {
	return &EmailClient_SendAccessRequestNotification_Call{Call: _e.mock.On("SendAccessRequestNotification", ctx, to, subject, email, reason)}
}

func (_c *EmailClient_SendAccessRequestNotification_Call) Run(run func(ctx context.Context, to []string, subject string, email string, reason string)) *EmailClient_SendAccessRequestNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EmailClient_SendAccessRequestNotification_Call) Return(err error) *EmailClient_SendAccessRequestNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailClient_SendAccessRequestNotification_Call) RunAndReturn(run func(ctx context.Context, to []string, subject string, email string, reason string) error) *EmailClient_SendAccessRequestNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendDeregistrationNotification provides a mock function for the type EmailClient
func (_mock *EmailClient) SendDeregistrationNotification(ctx context.Context, to []string, subject string, name string, reason string, happeningTitle string) error {
	ret := _mock.Called(ctx, to, subject, name, reason, happeningTitle)

	if len(ret) == 0 {
		panic("no return value specified for SendDeregistrationNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, subject, name, reason, happeningTitle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailClient_SendDeregistrationNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDeregistrationNotification'
type EmailClient_SendDeregistrationNotification_Call struct {
	*mock.Call
}

// SendDeregistrationNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - to []string
//   - subject string
//   - name string
//   - reason string
//   - happeningTitle string
func (_e *EmailClient_Expecter) SendDeregistrationNotification(ctx interface{}, to interface{}, subject interface{}, name interface{}, reason interface{}, happeningTitle interface{}) *EmailClient_SendDeregistrationNotification_Call {
	return &EmailClient_SendDeregistrationNotification_Call{Call: _e.mock.On("SendDeregistrationNotification", ctx, to, subject, name, reason, happeningTitle)}
}

func (_c *EmailClient_SendDeregistrationNotification_Call) Run(run func(ctx context.Context, to []string, subject string, name string, reason string, happeningTitle string)) *EmailClient_SendDeregistrationNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *EmailClient_SendDeregistrationNotification_Call) Return(err error) *EmailClient_SendDeregistrationNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailClient_SendDeregistrationNotification_Call) RunAndReturn(run func(ctx context.Context, to []string, subject string, name string, reason string, happeningTitle string) error) *EmailClient_SendDeregistrationNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendEmailVerification provides a mock function for the type EmailClient
func (_mock *EmailClient) SendEmailVerification(ctx context.Context, to []string, subject string, verificationURL string, firstName string) error {
	ret := _mock.Called(ctx, to, subject, verificationURL, firstName)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, subject, verificationURL, firstName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailClient_SendEmailVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailVerification'
type EmailClient_SendEmailVerification_Call struct {
	*mock.Call
}

// SendEmailVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - to []string
//   - subject string
//   - verificationURL string
//   - firstName string
func (_e *EmailClient_Expecter) SendEmailVerification(ctx interface{}, to interface{}, subject interface{}, verificationURL interface{}, firstName interface{}) *EmailClient_SendEmailVerification_Call {
	return &EmailClient_SendEmailVerification_Call{Call: _e.mock.On("SendEmailVerification", ctx, to, subject, verificationURL, firstName)}
}

func (_c *EmailClient_SendEmailVerification_Call) Run(run func(ctx context.Context, to []string, subject string, verificationURL string, firstName string)) *EmailClient_SendEmailVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EmailClient_SendEmailVerification_Call) Return(err error) *EmailClient_SendEmailVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailClient_SendEmailVerification_Call) RunAndReturn(run func(ctx context.Context, to []string, subject string, verificationURL string, firstName string) error) *EmailClient_SendEmailVerification_Call {
	_c.Call.Return(run)
	return _c
}

// SendGotSpotNotification provides a mock function for the type EmailClient
func (_mock *EmailClient) SendGotSpotNotification(ctx context.Context, to []string, subject string, name string, happeningTitle string) error {
	ret := _mock.Called(ctx, to, subject, name, happeningTitle)

	if len(ret) == 0 {
		panic("no return value specified for SendGotSpotNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, subject, name, happeningTitle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailClient_SendGotSpotNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendGotSpotNotification'
type EmailClient_SendGotSpotNotification_Call struct {
	*mock.Call
}

// SendGotSpotNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - to []string
//   - subject string
//   - name string
//   - happeningTitle string
func (_e *EmailClient_Expecter) SendGotSpotNotification(ctx interface{}, to interface{}, subject interface{}, name interface{}, happeningTitle interface{}) *EmailClient_SendGotSpotNotification_Call {
	return &EmailClient_SendGotSpotNotification_Call{Call: _e.mock.On("SendGotSpotNotification", ctx, to, subject, name, happeningTitle)}
}

func (_c *EmailClient_SendGotSpotNotification_Call) Run(run func(ctx context.Context, to []string, subject string, name string, happeningTitle string)) *EmailClient_SendGotSpotNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EmailClient_SendGotSpotNotification_Call) Return(err error) *EmailClient_SendGotSpotNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailClient_SendGotSpotNotification_Call) RunAndReturn(run func(ctx context.Context, to []string, subject string, name string, happeningTitle string) error) *EmailClient_SendGotSpotNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendMagicLink provides a mock function for the type EmailClient
func (_mock *EmailClient) SendMagicLink(ctx context.Context, to []string, subject string, magicLinkURL string, code string, firstName string) error {
	ret := _mock.Called(ctx, to, subject, magicLinkURL, code, firstName)

	if len(ret) == 0 {
		panic("no return value specified for SendMagicLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, subject, magicLinkURL, code, firstName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailClient_SendMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMagicLink'
type EmailClient_SendMagicLink_Call struct {
	*mock.Call
}

// SendMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - to []string
//   - subject string
//   - magicLinkURL string
//   - code string
//   - firstName string
func (_e *EmailClient_Expecter) SendMagicLink(ctx interface{}, to interface{}, subject interface{}, magicLinkURL interface{}, code interface{}, firstName interface{}) *EmailClient_SendMagicLink_Call {
	return &EmailClient_SendMagicLink_Call{Call: _e.mock.On("SendMagicLink", ctx, to, subject, magicLinkURL, code, firstName)}
}

func (_c *EmailClient_SendMagicLink_Call) Run(run func(ctx context.Context, to []string, subject string, magicLinkURL string, code string, firstName string)) *EmailClient_SendMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *EmailClient_SendMagicLink_Call) Return(err error) *EmailClient_SendMagicLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailClient_SendMagicLink_Call) RunAndReturn(run func(ctx context.Context, to []string, subject string, magicLinkURL string, code string, firstName string) error) *EmailClient_SendMagicLink_Call {
	_c.Call.Return(run)
	return _c
}

// SendRegistrationConfirmation provides a mock function for the type EmailClient
func (_mock *EmailClient) SendRegistrationConfirmation(ctx context.Context, to []string, subject string, title string, isBedpres bool) error {
	ret := _mock.Called(ctx, to, subject, title, isBedpres)

	if len(ret) == 0 {
		panic("no return value specified for SendRegistrationConfirmation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string, bool) error); ok {
		r0 = returnFunc(ctx, to, subject, title, isBedpres)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailClient_SendRegistrationConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRegistrationConfirmation'
type EmailClient_SendRegistrationConfirmation_Call struct {
	*mock.Call
}

// SendRegistrationConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - to []string
//   - subject string
//   - title string
//   - isBedpres bool
func (_e *EmailClient_Expecter) SendRegistrationConfirmation(ctx interface{}, to interface{}, subject interface{}, title interface{}, isBedpres interface{}) *EmailClient_SendRegistrationConfirmation_Call {
	return &EmailClient_SendRegistrationConfirmation_Call{Call: _e.mock.On("SendRegistrationConfirmation", ctx, to, subject, title, isBedpres)}
}

func (_c *EmailClient_SendRegistrationConfirmation_Call) Run(run func(ctx context.Context, to []string, subject string, title string, isBedpres bool)) *EmailClient_SendRegistrationConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EmailClient_SendRegistrationConfirmation_Call) Return(err error) *EmailClient_SendRegistrationConfirmation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailClient_SendRegistrationConfirmation_Call) RunAndReturn(run func(ctx context.Context, to []string, subject string, title string, isBedpres bool) error) *EmailClient_SendRegistrationConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// SendStrikeNotification provides a mock function for the type EmailClient
func (_mock *EmailClient) SendStrikeNotification(ctx context.Context, to []string, subject string, name string, reason string, amount int, isBanned bool) error {
	ret := _mock.Called(ctx, to, subject, name, reason, amount, isBanned)

	if len(ret) == 0 {
		panic("no return value specified for SendStrikeNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, string, string, int, bool) error); ok {
		r0 = returnFunc(ctx, to, subject, name, reason, amount, isBanned)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailClient_SendStrikeNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStrikeNotification'
type EmailClient_SendStrikeNotification_Call struct {
	*mock.Call
}

// SendStrikeNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - to []string
//   - subject string
//   - name string
//   - reason string
//   - amount int
//   - isBanned bool
func (_e *EmailClient_Expecter) SendStrikeNotification(ctx interface{}, to interface{}, subject interface{}, name interface{}, reason interface{}, amount interface{}, isBanned interface{}) *EmailClient_SendStrikeNotification_Call {
	return &EmailClient_SendStrikeNotification_Call{Call: _e.mock.On("SendStrikeNotification", ctx, to, subject, name, reason, amount, isBanned)}
}

func (_c *EmailClient_SendStrikeNotification_Call) Run(run func(ctx context.Context, to []string, subject string, name string, reason string, amount int, isBanned bool)) *EmailClient_SendStrikeNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *EmailClient_SendStrikeNotification_Call) Return(err error) *EmailClient_SendStrikeNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailClient_SendStrikeNotification_Call) RunAndReturn(run func(ctx context.Context, to []string, subject string, name string, reason string, amount int, isBanned bool) error) *EmailClient_SendStrikeNotification_Call {
	_c.Call.Return(run)
	return _c
}
