// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewGroupRepo creates a new instance of GroupRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupRepo {
	mock := &GroupRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GroupRepo is an autogenerated mock type for the GroupRepo type
type GroupRepo struct {
	mock.Mock
}

type GroupRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *GroupRepo) EXPECT() *GroupRepo_Expecter {
	return &GroupRepo_Expecter{mock: &_m.Mock}
}

// AddUserToGroup provides a mock function for the type GroupRepo
func (_mock *GroupRepo) AddUserToGroup(ctx context.Context, groupID string, userID string) error {
	ret := _mock.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, groupID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GroupRepo_AddUserToGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToGroup'
type GroupRepo_AddUserToGroup_Call struct {
	*mock.Call
}

// AddUserToGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
//   - userID string
func (_e *GroupRepo_Expecter) AddUserToGroup(ctx interface{}, groupID interface{}, userID interface{}) *GroupRepo_AddUserToGroup_Call {
	return &GroupRepo_AddUserToGroup_Call{Call: _e.mock.On("AddUserToGroup", ctx, groupID, userID)}
}

func (_c *GroupRepo_AddUserToGroup_Call) Run(run func(ctx context.Context, groupID string, userID string)) *GroupRepo_AddUserToGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GroupRepo_AddUserToGroup_Call) Return(err error) *GroupRepo_AddUserToGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GroupRepo_AddUserToGroup_Call) RunAndReturn(run func(ctx context.Context, groupID string, userID string) error) *GroupRepo_AddUserToGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function for the type GroupRepo
func (_mock *GroupRepo) CreateGroup(ctx context.Context, group model.NewGroup) (model.Group, error) {
	ret := _mock.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 model.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.NewGroup) (model.Group, error)); ok {
		return returnFunc(ctx, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.NewGroup) model.Group); ok {
		r0 = returnFunc(ctx, group)
	} else {
		r0 = ret.Get(0).(model.Group)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.NewGroup) error); ok {
		r1 = returnFunc(ctx, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GroupRepo_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type GroupRepo_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - group model.NewGroup
func (_e *GroupRepo_Expecter) CreateGroup(ctx interface{}, group interface{}) *GroupRepo_CreateGroup_Call {
	return &GroupRepo_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, group)}
}

func (_c *GroupRepo_CreateGroup_Call) Run(run func(ctx context.Context, group model.NewGroup)) *GroupRepo_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.NewGroup
		if args[1] != nil {
			arg1 = args[1].(model.NewGroup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GroupRepo_CreateGroup_Call) Return(group1 model.Group, err error) *GroupRepo_CreateGroup_Call {
	_c.Call.Return(group1, err)
	return _c
}

func (_c *GroupRepo_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, group model.NewGroup) (model.Group, error)) *GroupRepo_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroup provides a mock function for the type GroupRepo
func (_mock *GroupRepo) DeleteGroup(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GroupRepo_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type GroupRepo_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *GroupRepo_Expecter) DeleteGroup(ctx interface{}, id interface{}) *GroupRepo_DeleteGroup_Call {
	return &GroupRepo_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", ctx, id)}
}

func (_c *GroupRepo_DeleteGroup_Call) Run(run func(ctx context.Context, id string)) *GroupRepo_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GroupRepo_DeleteGroup_Call) Return(err error) *GroupRepo_DeleteGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GroupRepo_DeleteGroup_Call) RunAndReturn(run func(ctx context.Context, id string) error) *GroupRepo_DeleteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllGroups provides a mock function for the type GroupRepo
func (_mock *GroupRepo) GetAllGroups(ctx context.Context) ([]model.Group, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllGroups")
	}

	var r0 []model.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Group, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Group); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GroupRepo_GetAllGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllGroups'
type GroupRepo_GetAllGroups_Call struct {
	*mock.Call
}

// GetAllGroups is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GroupRepo_Expecter) GetAllGroups(ctx interface{}) *GroupRepo_GetAllGroups_Call {
	return &GroupRepo_GetAllGroups_Call{Call: _e.mock.On("GetAllGroups", ctx)}
}

func (_c *GroupRepo_GetAllGroups_Call) Run(run func(ctx context.Context)) *GroupRepo_GetAllGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GroupRepo_GetAllGroups_Call) Return(groups []model.Group, err error) *GroupRepo_GetAllGroups_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *GroupRepo_GetAllGroups_Call) RunAndReturn(run func(ctx context.Context) ([]model.Group, error)) *GroupRepo_GetAllGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupByID provides a mock function for the type GroupRepo
func (_mock *GroupRepo) GetGroupByID(ctx context.Context, id string) (model.Group, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupByID")
	}

	var r0 model.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Group, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Group); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Group)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GroupRepo_GetGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupByID'
type GroupRepo_GetGroupByID_Call struct {
	*mock.Call
}

// GetGroupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *GroupRepo_Expecter) GetGroupByID(ctx interface{}, id interface{}) *GroupRepo_GetGroupByID_Call {
	return &GroupRepo_GetGroupByID_Call{Call: _e.mock.On("GetGroupByID", ctx, id)}
}

func (_c *GroupRepo_GetGroupByID_Call) Run(run func(ctx context.Context, id string)) *GroupRepo_GetGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GroupRepo_GetGroupByID_Call) Return(group model.Group, err error) *GroupRepo_GetGroupByID_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *GroupRepo_GetGroupByID_Call) RunAndReturn(run func(ctx context.Context, id string) (model.Group, error)) *GroupRepo_GetGroupByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupMembers provides a mock function for the type GroupRepo
func (_mock *GroupRepo) GetGroupMembers(ctx context.Context, groupID string) ([]model.GroupMember, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupMembers")
	}

	var r0 []model.GroupMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.GroupMember, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.GroupMember); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GroupMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GroupRepo_GetGroupMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupMembers'
type GroupRepo_GetGroupMembers_Call struct {
	*mock.Call
}

// GetGroupMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
func (_e *GroupRepo_Expecter) GetGroupMembers(ctx interface{}, groupID interface{}) *GroupRepo_GetGroupMembers_Call {
	return &GroupRepo_GetGroupMembers_Call{Call: _e.mock.On("GetGroupMembers", ctx, groupID)}
}

func (_c *GroupRepo_GetGroupMembers_Call) Run(run func(ctx context.Context, groupID string)) *GroupRepo_GetGroupMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GroupRepo_GetGroupMembers_Call) Return(groupMembers []model.GroupMember, err error) *GroupRepo_GetGroupMembers_Call {
	_c.Call.Return(groupMembers, err)
	return _c
}

func (_c *GroupRepo_GetGroupMembers_Call) RunAndReturn(run func(ctx context.Context, groupID string) ([]model.GroupMember, error)) *GroupRepo_GetGroupMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserGroupMembership provides a mock function for the type GroupRepo
func (_mock *GroupRepo) GetUserGroupMembership(ctx context.Context, groupID string, userID string) (*model.UsersToGroups, error) {
	ret := _mock.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGroupMembership")
	}

	var r0 *model.UsersToGroups
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.UsersToGroups, error)); ok {
		return returnFunc(ctx, groupID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.UsersToGroups); ok {
		r0 = returnFunc(ctx, groupID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UsersToGroups)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, groupID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GroupRepo_GetUserGroupMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGroupMembership'
type GroupRepo_GetUserGroupMembership_Call struct {
	*mock.Call
}

// GetUserGroupMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
//   - userID string
func (_e *GroupRepo_Expecter) GetUserGroupMembership(ctx interface{}, groupID interface{}, userID interface{}) *GroupRepo_GetUserGroupMembership_Call {
	return &GroupRepo_GetUserGroupMembership_Call{Call: _e.mock.On("GetUserGroupMembership", ctx, groupID, userID)}
}

func (_c *GroupRepo_GetUserGroupMembership_Call) Run(run func(ctx context.Context, groupID string, userID string)) *GroupRepo_GetUserGroupMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GroupRepo_GetUserGroupMembership_Call) Return(usersToGroups *model.UsersToGroups, err error) *GroupRepo_GetUserGroupMembership_Call {
	_c.Call.Return(usersToGroups, err)
	return _c
}

func (_c *GroupRepo_GetUserGroupMembership_Call) RunAndReturn(run func(ctx context.Context, groupID string, userID string) (*model.UsersToGroups, error)) *GroupRepo_GetUserGroupMembership_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserFromGroup provides a mock function for the type GroupRepo
func (_mock *GroupRepo) RemoveUserFromGroup(ctx context.Context, groupID string, userID string) error {
	ret := _mock.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserFromGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, groupID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GroupRepo_RemoveUserFromGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserFromGroup'
type GroupRepo_RemoveUserFromGroup_Call struct {
	*mock.Call
}

// RemoveUserFromGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
//   - userID string
func (_e *GroupRepo_Expecter) RemoveUserFromGroup(ctx interface{}, groupID interface{}, userID interface{}) *GroupRepo_RemoveUserFromGroup_Call {
	return &GroupRepo_RemoveUserFromGroup_Call{Call: _e.mock.On("RemoveUserFromGroup", ctx, groupID, userID)}
}

func (_c *GroupRepo_RemoveUserFromGroup_Call) Run(run func(ctx context.Context, groupID string, userID string)) *GroupRepo_RemoveUserFromGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GroupRepo_RemoveUserFromGroup_Call) Return(err error) *GroupRepo_RemoveUserFromGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GroupRepo_RemoveUserFromGroup_Call) RunAndReturn(run func(ctx context.Context, groupID string, userID string) error) *GroupRepo_RemoveUserFromGroup_Call {
	_c.Call.Return(run)
	return _c
}

// SetGroupMemberLeader provides a mock function for the type GroupRepo
func (_mock *GroupRepo) SetGroupMemberLeader(ctx context.Context, groupID string, userID string, isLeader bool) error {
	ret := _mock.Called(ctx, groupID, userID, isLeader)

	if len(ret) == 0 {
		panic("no return value specified for SetGroupMemberLeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = returnFunc(ctx, groupID, userID, isLeader)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GroupRepo_SetGroupMemberLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGroupMemberLeader'
type GroupRepo_SetGroupMemberLeader_Call struct {
	*mock.Call
}

// SetGroupMemberLeader is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
//   - userID string
//   - isLeader bool
func (_e *GroupRepo_Expecter) SetGroupMemberLeader(ctx interface{}, groupID interface{}, userID interface{}, isLeader interface{}) *GroupRepo_SetGroupMemberLeader_Call {
	return &GroupRepo_SetGroupMemberLeader_Call{Call: _e.mock.On("SetGroupMemberLeader", ctx, groupID, userID, isLeader)}
}

func (_c *GroupRepo_SetGroupMemberLeader_Call) Run(run func(ctx context.Context, groupID string, userID string, isLeader bool)) *GroupRepo_SetGroupMemberLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *GroupRepo_SetGroupMemberLeader_Call) Return(err error) *GroupRepo_SetGroupMemberLeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GroupRepo_SetGroupMemberLeader_Call) RunAndReturn(run func(ctx context.Context, groupID string, userID string, isLeader bool) error) *GroupRepo_SetGroupMemberLeader_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function for the type GroupRepo
func (_mock *GroupRepo) UpdateGroup(ctx context.Context, group model.Group) (model.Group, error) {
	ret := _mock.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 model.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Group) (model.Group, error)); ok {
		return returnFunc(ctx, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Group) model.Group); ok {
		r0 = returnFunc(ctx, group)
	} else {
		r0 = ret.Get(0).(model.Group)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Group) error); ok {
		r1 = returnFunc(ctx, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GroupRepo_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type GroupRepo_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - group model.Group
func (_e *GroupRepo_Expecter) UpdateGroup(ctx interface{}, group interface{}) *GroupRepo_UpdateGroup_Call {
	return &GroupRepo_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, group)}
}

func (_c *GroupRepo_UpdateGroup_Call) Run(run func(ctx context.Context, group model.Group)) *GroupRepo_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Group
		if args[1] != nil {
			arg1 = args[1].(model.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GroupRepo_UpdateGroup_Call) Return(group1 model.Group, err error) *GroupRepo_UpdateGroup_Call {
	_c.Call.Return(group1, err)
	return _c
}

func (_c *GroupRepo_UpdateGroup_Call) RunAndReturn(run func(ctx context.Context, group model.Group) (model.Group, error)) *GroupRepo_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}
