// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewKVRepo creates a new instance of KVRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKVRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *KVRepo {
	mock := &KVRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KVRepo is an autogenerated mock type for the KVRepo type
type KVRepo struct {
	mock.Mock
}

type KVRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *KVRepo) EXPECT() *KVRepo_Expecter {
	return &KVRepo_Expecter{mock: &_m.Mock}
}

// DeleteExpired provides a mock function for the type KVRepo
func (_mock *KVRepo) DeleteExpired(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KVRepo_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type KVRepo_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *KVRepo_Expecter) DeleteExpired(ctx interface{}) *KVRepo_DeleteExpired_Call {
	return &KVRepo_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *KVRepo_DeleteExpired_Call) Run(run func(ctx context.Context)) *KVRepo_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KVRepo_DeleteExpired_Call) Return(n int64, err error) *KVRepo_DeleteExpired_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *KVRepo_DeleteExpired_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *KVRepo_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}
