// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewNotificationRepo creates a new instance of NotificationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepo {
	mock := &NotificationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationRepo is an autogenerated mock type for the NotificationRepo type
type NotificationRepo struct {
	mock.Mock
}

type NotificationRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationRepo) EXPECT() *NotificationRepo_Expecter {
	return &NotificationRepo_Expecter{mock: &_m.Mock}
}

// Archive provides a mock function for the type NotificationRepo
func (_mock *NotificationRepo) Archive(ctx context.Context, id int, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Archive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationRepo_Archive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Archive'
type NotificationRepo_Archive_Call struct {
	*mock.Call
}

// Archive is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID string
func (_e *NotificationRepo_Expecter) Archive(ctx interface{}, id interface{}, userID interface{}) *NotificationRepo_Archive_Call {
	return &NotificationRepo_Archive_Call{Call: _e.mock.On("Archive", ctx, id, userID)}
}

func (_c *NotificationRepo_Archive_Call) Run(run func(ctx context.Context, id int, userID string)) *NotificationRepo_Archive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NotificationRepo_Archive_Call) Return(err error) *NotificationRepo_Archive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationRepo_Archive_Call) RunAndReturn(run func(ctx context.Context, id int, userID string) error) *NotificationRepo_Archive_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type NotificationRepo
func (_mock *NotificationRepo) Create(ctx context.Context, userID string, notifType string, title string, content *string, link *string) error {
	ret := _mock.Called(ctx, userID, notifType, title, content, link)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string, *string) error); ok {
		r0 = returnFunc(ctx, userID, notifType, title, content, link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NotificationRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - notifType string
//   - title string
//   - content *string
//   - link *string
func (_e *NotificationRepo_Expecter) Create(ctx interface{}, userID interface{}, notifType interface{}, title interface{}, content interface{}, link interface{}) *NotificationRepo_Create_Call {
	return &NotificationRepo_Create_Call{Call: _e.mock.On("Create", ctx, userID, notifType, title, content, link)}
}

func (_c *NotificationRepo_Create_Call) Run(run func(ctx context.Context, userID string, notifType string, title string, content *string, link *string)) *NotificationRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *NotificationRepo_Create_Call) Return(err error) *NotificationRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationRepo_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, notifType string, title string, content *string, link *string) error) *NotificationRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type NotificationRepo
func (_mock *NotificationRepo) GetByUserID(ctx context.Context, userID string) ([]model.Notification, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []model.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Notification, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Notification); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationRepo_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type NotificationRepo_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *NotificationRepo_Expecter) GetByUserID(ctx interface{}, userID interface{}) *NotificationRepo_GetByUserID_Call {
	return &NotificationRepo_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *NotificationRepo_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *NotificationRepo_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationRepo_GetByUserID_Call) Return(notifications []model.Notification, err error) *NotificationRepo_GetByUserID_Call {
	_c.Call.Return(notifications, err)
	return _c
}

func (_c *NotificationRepo_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]model.Notification, error)) *NotificationRepo_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSeen provides a mock function for the type NotificationRepo
func (_mock *NotificationRepo) MarkSeen(ctx context.Context, id int, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkSeen")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationRepo_MarkSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSeen'
type NotificationRepo_MarkSeen_Call struct {
	*mock.Call
}

// MarkSeen is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID string
func (_e *NotificationRepo_Expecter) MarkSeen(ctx interface{}, id interface{}, userID interface{}) *NotificationRepo_MarkSeen_Call {
	return &NotificationRepo_MarkSeen_Call{Call: _e.mock.On("MarkSeen", ctx, id, userID)}
}

func (_c *NotificationRepo_MarkSeen_Call) Run(run func(ctx context.Context, id int, userID string)) *NotificationRepo_MarkSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NotificationRepo_MarkSeen_Call) Return(err error) *NotificationRepo_MarkSeen_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationRepo_MarkSeen_Call) RunAndReturn(run func(ctx context.Context, id int, userID string) error) *NotificationRepo_MarkSeen_Call {
	_c.Call.Return(run)
	return _c
}
