// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/port"

	mock "github.com/stretchr/testify/mock"
)

// NewOAuth2Provider creates a new instance of OAuth2Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuth2Provider(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuth2Provider {
	mock := &OAuth2Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuth2Provider is an autogenerated mock type for the OAuth2Provider type
type OAuth2Provider struct {
	mock.Mock
}

type OAuth2Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuth2Provider) EXPECT() *OAuth2Provider_Expecter {
	return &OAuth2Provider_Expecter{mock: &_m.Mock}
}

// CreateAuthorizationURL provides a mock function for the type OAuth2Provider
func (_mock *OAuth2Provider) CreateAuthorizationURL(state string) (string, error) {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthorizationURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(state)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuth2Provider_CreateAuthorizationURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthorizationURL'
type OAuth2Provider_CreateAuthorizationURL_Call struct {
	*mock.Call
}

// CreateAuthorizationURL is a helper method to define mock.On call
//   - state string
func (_e *OAuth2Provider_Expecter) CreateAuthorizationURL(state interface{}) *OAuth2Provider_CreateAuthorizationURL_Call {
	return &OAuth2Provider_CreateAuthorizationURL_Call{Call: _e.mock.On("CreateAuthorizationURL", state)}
}

func (_c *OAuth2Provider_CreateAuthorizationURL_Call) Run(run func(state string)) *OAuth2Provider_CreateAuthorizationURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OAuth2Provider_CreateAuthorizationURL_Call) Return(s string, err error) *OAuth2Provider_CreateAuthorizationURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *OAuth2Provider_CreateAuthorizationURL_Call) RunAndReturn(run func(state string) (string, error)) *OAuth2Provider_CreateAuthorizationURL_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeCode provides a mock function for the type OAuth2Provider
func (_mock *OAuth2Provider) ExchangeCode(ctx context.Context, code string) (*port.OAuth2Tokens, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCode")
	}

	var r0 *port.OAuth2Tokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*port.OAuth2Tokens, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *port.OAuth2Tokens); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.OAuth2Tokens)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuth2Provider_ExchangeCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCode'
type OAuth2Provider_ExchangeCode_Call struct {
	*mock.Call
}

// ExchangeCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *OAuth2Provider_Expecter) ExchangeCode(ctx interface{}, code interface{}) *OAuth2Provider_ExchangeCode_Call {
	return &OAuth2Provider_ExchangeCode_Call{Call: _e.mock.On("ExchangeCode", ctx, code)}
}

func (_c *OAuth2Provider_ExchangeCode_Call) Run(run func(ctx context.Context, code string)) *OAuth2Provider_ExchangeCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuth2Provider_ExchangeCode_Call) Return(oAuth2Tokens *port.OAuth2Tokens, err error) *OAuth2Provider_ExchangeCode_Call {
	_c.Call.Return(oAuth2Tokens, err)
	return _c
}

func (_c *OAuth2Provider_ExchangeCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*port.OAuth2Tokens, error)) *OAuth2Provider_ExchangeCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function for the type OAuth2Provider
func (_mock *OAuth2Provider) GetUserInfo(ctx context.Context, accessToken string) (*port.OAuth2UserInfo, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *port.OAuth2UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*port.OAuth2UserInfo, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *port.OAuth2UserInfo); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.OAuth2UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuth2Provider_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type OAuth2Provider_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *OAuth2Provider_Expecter) GetUserInfo(ctx interface{}, accessToken interface{}) *OAuth2Provider_GetUserInfo_Call {
	return &OAuth2Provider_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, accessToken)}
}

func (_c *OAuth2Provider_GetUserInfo_Call) Run(run func(ctx context.Context, accessToken string)) *OAuth2Provider_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuth2Provider_GetUserInfo_Call) Return(oAuth2UserInfo *port.OAuth2UserInfo, err error) *OAuth2Provider_GetUserInfo_Call {
	_c.Call.Return(oAuth2UserInfo, err)
	return _c
}

func (_c *OAuth2Provider_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (*port.OAuth2UserInfo, error)) *OAuth2Provider_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}
