// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewQuoteRepo creates a new instance of QuoteRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuoteRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuoteRepo {
	mock := &QuoteRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QuoteRepo is an autogenerated mock type for the QuoteRepo type
type QuoteRepo struct {
	mock.Mock
}

type QuoteRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *QuoteRepo) EXPECT() *QuoteRepo_Expecter {
	return &QuoteRepo_Expecter{mock: &_m.Mock}
}

// CreateQuote provides a mock function for the type QuoteRepo
func (_mock *QuoteRepo) CreateQuote(ctx context.Context, quote model.Quote, submittedBy string) error {
	ret := _mock.Called(ctx, quote, submittedBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Quote, string) error); ok {
		r0 = returnFunc(ctx, quote, submittedBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuoteRepo_CreateQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQuote'
type QuoteRepo_CreateQuote_Call struct {
	*mock.Call
}

// CreateQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - quote model.Quote
//   - submittedBy string
func (_e *QuoteRepo_Expecter) CreateQuote(ctx interface{}, quote interface{}, submittedBy interface{}) *QuoteRepo_CreateQuote_Call {
	return &QuoteRepo_CreateQuote_Call{Call: _e.mock.On("CreateQuote", ctx, quote, submittedBy)}
}

func (_c *QuoteRepo_CreateQuote_Call) Run(run func(ctx context.Context, quote model.Quote, submittedBy string)) *QuoteRepo_CreateQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Quote
		if args[1] != nil {
			arg1 = args[1].(model.Quote)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QuoteRepo_CreateQuote_Call) Return(err error) *QuoteRepo_CreateQuote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuoteRepo_CreateQuote_Call) RunAndReturn(run func(ctx context.Context, quote model.Quote, submittedBy string) error) *QuoteRepo_CreateQuote_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQuote provides a mock function for the type QuoteRepo
func (_mock *QuoteRepo) DeleteQuote(ctx context.Context, quoteID string) error {
	ret := _mock.Called(ctx, quoteID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, quoteID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuoteRepo_DeleteQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuote'
type QuoteRepo_DeleteQuote_Call struct {
	*mock.Call
}

// DeleteQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - quoteID string
func (_e *QuoteRepo_Expecter) DeleteQuote(ctx interface{}, quoteID interface{}) *QuoteRepo_DeleteQuote_Call {
	return &QuoteRepo_DeleteQuote_Call{Call: _e.mock.On("DeleteQuote", ctx, quoteID)}
}

func (_c *QuoteRepo_DeleteQuote_Call) Run(run func(ctx context.Context, quoteID string)) *QuoteRepo_DeleteQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuoteRepo_DeleteQuote_Call) Return(err error) *QuoteRepo_DeleteQuote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuoteRepo_DeleteQuote_Call) RunAndReturn(run func(ctx context.Context, quoteID string) error) *QuoteRepo_DeleteQuote_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotes provides a mock function for the type QuoteRepo
func (_mock *QuoteRepo) GetQuotes(ctx context.Context) ([]model.Quote, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotes")
	}

	var r0 []model.Quote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Quote, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Quote); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Quote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuoteRepo_GetQuotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotes'
type QuoteRepo_GetQuotes_Call struct {
	*mock.Call
}

// GetQuotes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *QuoteRepo_Expecter) GetQuotes(ctx interface{}) *QuoteRepo_GetQuotes_Call {
	return &QuoteRepo_GetQuotes_Call{Call: _e.mock.On("GetQuotes", ctx)}
}

func (_c *QuoteRepo_GetQuotes_Call) Run(run func(ctx context.Context)) *QuoteRepo_GetQuotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *QuoteRepo_GetQuotes_Call) Return(quotes []model.Quote, err error) *QuoteRepo_GetQuotes_Call {
	_c.Call.Return(quotes, err)
	return _c
}

func (_c *QuoteRepo_GetQuotes_Call) RunAndReturn(run func(ctx context.Context) ([]model.Quote, error)) *QuoteRepo_GetQuotes_Call {
	_c.Call.Return(run)
	return _c
}
