// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewRegistrationRepo creates a new instance of RegistrationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistrationRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistrationRepo {
	mock := &RegistrationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RegistrationRepo is an autogenerated mock type for the RegistrationRepo type
type RegistrationRepo struct {
	mock.Mock
}

type RegistrationRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistrationRepo) EXPECT() *RegistrationRepo_Expecter {
	return &RegistrationRepo_Expecter{mock: &_m.Mock}
}

// CreateRegistration provides a mock function for the type RegistrationRepo
func (_mock *RegistrationRepo) CreateRegistration(ctx context.Context, userID string, happening model.Happening, spotRanges []model.SpotRange, hostGroups []string, canSkipSpotRange bool) (*model.Registration, bool, error) {
	ret := _mock.Called(ctx, userID, happening, spotRanges, hostGroups, canSkipSpotRange)

	if len(ret) == 0 {
		panic("no return value specified for CreateRegistration")
	}

	var r0 *model.Registration
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Happening, []model.SpotRange, []string, bool) (*model.Registration, bool, error)); ok {
		return returnFunc(ctx, userID, happening, spotRanges, hostGroups, canSkipSpotRange)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Happening, []model.SpotRange, []string, bool) *model.Registration); ok {
		r0 = returnFunc(ctx, userID, happening, spotRanges, hostGroups, canSkipSpotRange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Registration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Happening, []model.SpotRange, []string, bool) bool); ok {
		r1 = returnFunc(ctx, userID, happening, spotRanges, hostGroups, canSkipSpotRange)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, model.Happening, []model.SpotRange, []string, bool) error); ok {
		r2 = returnFunc(ctx, userID, happening, spotRanges, hostGroups, canSkipSpotRange)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RegistrationRepo_CreateRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRegistration'
type RegistrationRepo_CreateRegistration_Call struct {
	*mock.Call
}

// CreateRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - happening model.Happening
//   - spotRanges []model.SpotRange
//   - hostGroups []string
//   - canSkipSpotRange bool
func (_e *RegistrationRepo_Expecter) CreateRegistration(ctx interface{}, userID interface{}, happening interface{}, spotRanges interface{}, hostGroups interface{}, canSkipSpotRange interface{}) *RegistrationRepo_CreateRegistration_Call {
	return &RegistrationRepo_CreateRegistration_Call{Call: _e.mock.On("CreateRegistration", ctx, userID, happening, spotRanges, hostGroups, canSkipSpotRange)}
}

func (_c *RegistrationRepo_CreateRegistration_Call) Run(run func(ctx context.Context, userID string, happening model.Happening, spotRanges []model.SpotRange, hostGroups []string, canSkipSpotRange bool)) *RegistrationRepo_CreateRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Happening
		if args[2] != nil {
			arg2 = args[2].(model.Happening)
		}
		var arg3 []model.SpotRange
		if args[3] != nil {
			arg3 = args[3].([]model.SpotRange)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *RegistrationRepo_CreateRegistration_Call) Return(registration *model.Registration, b bool, err error) *RegistrationRepo_CreateRegistration_Call {
	_c.Call.Return(registration, b, err)
	return _c
}

func (_c *RegistrationRepo_CreateRegistration_Call) RunAndReturn(run func(ctx context.Context, userID string, happening model.Happening, spotRanges []model.SpotRange, hostGroups []string, canSkipSpotRange bool) (*model.Registration, bool, error)) *RegistrationRepo_CreateRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserAndHappening provides a mock function for the type RegistrationRepo
func (_mock *RegistrationRepo) GetByUserAndHappening(ctx context.Context, userID string, happeningID string) (*model.Registration, error) {
	ret := _mock.Called(ctx, userID, happeningID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndHappening")
	}

	var r0 *model.Registration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Registration, error)); ok {
		return returnFunc(ctx, userID, happeningID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Registration); ok {
		r0 = returnFunc(ctx, userID, happeningID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Registration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, happeningID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RegistrationRepo_GetByUserAndHappening_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndHappening'
type RegistrationRepo_GetByUserAndHappening_Call struct {
	*mock.Call
}

// GetByUserAndHappening is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - happeningID string
func (_e *RegistrationRepo_Expecter) GetByUserAndHappening(ctx interface{}, userID interface{}, happeningID interface{}) *RegistrationRepo_GetByUserAndHappening_Call {
	return &RegistrationRepo_GetByUserAndHappening_Call{Call: _e.mock.On("GetByUserAndHappening", ctx, userID, happeningID)}
}

func (_c *RegistrationRepo_GetByUserAndHappening_Call) Run(run func(ctx context.Context, userID string, happeningID string)) *RegistrationRepo_GetByUserAndHappening_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RegistrationRepo_GetByUserAndHappening_Call) Return(registration *model.Registration, err error) *RegistrationRepo_GetByUserAndHappening_Call {
	_c.Call.Return(registration, err)
	return _c
}

func (_c *RegistrationRepo_GetByUserAndHappening_Call) RunAndReturn(run func(ctx context.Context, userID string, happeningID string) (*model.Registration, error)) *RegistrationRepo_GetByUserAndHappening_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAnswers provides a mock function for the type RegistrationRepo
func (_mock *RegistrationRepo) InsertAnswers(ctx context.Context, userID string, happeningID string, questions []model.QuestionAnswer) error {
	ret := _mock.Called(ctx, userID, happeningID, questions)

	if len(ret) == 0 {
		panic("no return value specified for InsertAnswers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []model.QuestionAnswer) error); ok {
		r0 = returnFunc(ctx, userID, happeningID, questions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RegistrationRepo_InsertAnswers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAnswers'
type RegistrationRepo_InsertAnswers_Call struct {
	*mock.Call
}

// InsertAnswers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - happeningID string
//   - questions []model.QuestionAnswer
func (_e *RegistrationRepo_Expecter) InsertAnswers(ctx interface{}, userID interface{}, happeningID interface{}, questions interface{}) *RegistrationRepo_InsertAnswers_Call {
	return &RegistrationRepo_InsertAnswers_Call{Call: _e.mock.On("InsertAnswers", ctx, userID, happeningID, questions)}
}

func (_c *RegistrationRepo_InsertAnswers_Call) Run(run func(ctx context.Context, userID string, happeningID string, questions []model.QuestionAnswer)) *RegistrationRepo_InsertAnswers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []model.QuestionAnswer
		if args[3] != nil {
			arg3 = args[3].([]model.QuestionAnswer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RegistrationRepo_InsertAnswers_Call) Return(err error) *RegistrationRepo_InsertAnswers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RegistrationRepo_InsertAnswers_Call) RunAndReturn(run func(ctx context.Context, userID string, happeningID string, questions []model.QuestionAnswer) error) *RegistrationRepo_InsertAnswers_Call {
	_c.Call.Return(run)
	return _c
}
