// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type UserRepo
func (_mock *UserRepo) CreateUser(ctx context.Context, user model.User) (model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *UserRepo_Expecter) CreateUser(ctx interface{}, user interface{}) *UserRepo_CreateUser_Call {
	return &UserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *UserRepo_CreateUser_Call) Run(run func(ctx context.Context, user model.User)) *UserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_CreateUser_Call) Return(user1 model.User, err error) *UserRepo_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user model.User) (model.User, error)) *UserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserAndAccount provides a mock function for the type UserRepo
func (_mock *UserRepo) CreateUserAndAccount(ctx context.Context, user model.User, account model.NewAccount) (model.User, error) {
	ret := _mock.Called(ctx, user, account)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserAndAccount")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User, model.NewAccount) (model.User, error)); ok {
		return returnFunc(ctx, user, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User, model.NewAccount) model.User); ok {
		r0 = returnFunc(ctx, user, account)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User, model.NewAccount) error); ok {
		r1 = returnFunc(ctx, user, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_CreateUserAndAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserAndAccount'
type UserRepo_CreateUserAndAccount_Call struct {
	*mock.Call
}

// CreateUserAndAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
//   - account model.NewAccount
func (_e *UserRepo_Expecter) CreateUserAndAccount(ctx interface{}, user interface{}, account interface{}) *UserRepo_CreateUserAndAccount_Call {
	return &UserRepo_CreateUserAndAccount_Call{Call: _e.mock.On("CreateUserAndAccount", ctx, user, account)}
}

func (_c *UserRepo_CreateUserAndAccount_Call) Run(run func(ctx context.Context, user model.User, account model.NewAccount)) *UserRepo_CreateUserAndAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		var arg2 model.NewAccount
		if args[2] != nil {
			arg2 = args[2].(model.NewAccount)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepo_CreateUserAndAccount_Call) Return(user1 model.User, err error) *UserRepo_CreateUserAndAccount_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepo_CreateUserAndAccount_Call) RunAndReturn(run func(ctx context.Context, user model.User, account model.NewAccount) (model.User, error)) *UserRepo_CreateUserAndAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type UserRepo
func (_mock *UserRepo) GetAllUsers(ctx context.Context) ([]model.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type UserRepo_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepo_Expecter) GetAllUsers(ctx interface{}) *UserRepo_GetAllUsers_Call {
	return &UserRepo_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx)}
}

func (_c *UserRepo_GetAllUsers_Call) Run(run func(ctx context.Context)) *UserRepo_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepo_GetAllUsers_Call) Return(users []model.User, err error) *UserRepo_GetAllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *UserRepo_GetAllUsers_Call) RunAndReturn(run func(ctx context.Context) ([]model.User, error)) *UserRepo_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type UserRepo
func (_mock *UserRepo) GetUserByEmail(ctx context.Context, email string) (model.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type UserRepo_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepo_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *UserRepo_GetUserByEmail_Call {
	return &UserRepo_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *UserRepo_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepo_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_GetUserByEmail_Call) Return(user model.User, err error) *UserRepo_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepo_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (model.User, error)) *UserRepo_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByFeideID provides a mock function for the type UserRepo
func (_mock *UserRepo) GetUserByFeideID(ctx context.Context, id string) (model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByFeideID")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_GetUserByFeideID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByFeideID'
type UserRepo_GetUserByFeideID_Call struct {
	*mock.Call
}

// GetUserByFeideID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserRepo_Expecter) GetUserByFeideID(ctx interface{}, id interface{}) *UserRepo_GetUserByFeideID_Call {
	return &UserRepo_GetUserByFeideID_Call{Call: _e.mock.On("GetUserByFeideID", ctx, id)}
}

func (_c *UserRepo_GetUserByFeideID_Call) Run(run func(ctx context.Context, id string)) *UserRepo_GetUserByFeideID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_GetUserByFeideID_Call) Return(user model.User, err error) *UserRepo_GetUserByFeideID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepo_GetUserByFeideID_Call) RunAndReturn(run func(ctx context.Context, id string) (model.User, error)) *UserRepo_GetUserByFeideID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type UserRepo
func (_mock *UserRepo) GetUserByID(ctx context.Context, id string) (model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type UserRepo_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserRepo_Expecter) GetUserByID(ctx interface{}, id interface{}) *UserRepo_GetUserByID_Call {
	return &UserRepo_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *UserRepo_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *UserRepo_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_GetUserByID_Call) Return(user model.User, err error) *UserRepo_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepo_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id string) (model.User, error)) *UserRepo_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserMemberships provides a mock function for the type UserRepo
func (_mock *UserRepo) GetUserMemberships(ctx context.Context, userID string) ([]string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserMemberships")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_GetUserMemberships_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserMemberships'
type UserRepo_GetUserMemberships_Call struct {
	*mock.Call
}

// GetUserMemberships is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRepo_Expecter) GetUserMemberships(ctx interface{}, userID interface{}) *UserRepo_GetUserMemberships_Call {
	return &UserRepo_GetUserMemberships_Call{Call: _e.mock.On("GetUserMemberships", ctx, userID)}
}

func (_c *UserRepo_GetUserMemberships_Call) Run(run func(ctx context.Context, userID string)) *UserRepo_GetUserMemberships_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_GetUserMemberships_Call) Return(strings []string, err error) *UserRepo_GetUserMemberships_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *UserRepo_GetUserMemberships_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]string, error)) *UserRepo_GetUserMemberships_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWithStrikeDetailsByID provides a mock function for the type UserRepo
func (_mock *UserRepo) GetUserWithStrikeDetailsByID(ctx context.Context, userID string) (*model.UserWithStrikeDetails, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithStrikeDetailsByID")
	}

	var r0 *model.UserWithStrikeDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.UserWithStrikeDetails, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.UserWithStrikeDetails); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserWithStrikeDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_GetUserWithStrikeDetailsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithStrikeDetailsByID'
type UserRepo_GetUserWithStrikeDetailsByID_Call struct {
	*mock.Call
}

// GetUserWithStrikeDetailsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRepo_Expecter) GetUserWithStrikeDetailsByID(ctx interface{}, userID interface{}) *UserRepo_GetUserWithStrikeDetailsByID_Call {
	return &UserRepo_GetUserWithStrikeDetailsByID_Call{Call: _e.mock.On("GetUserWithStrikeDetailsByID", ctx, userID)}
}

func (_c *UserRepo_GetUserWithStrikeDetailsByID_Call) Run(run func(ctx context.Context, userID string)) *UserRepo_GetUserWithStrikeDetailsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_GetUserWithStrikeDetailsByID_Call) Return(userWithStrikeDetails *model.UserWithStrikeDetails, err error) *UserRepo_GetUserWithStrikeDetailsByID_Call {
	_c.Call.Return(userWithStrikeDetails, err)
	return _c
}

func (_c *UserRepo_GetUserWithStrikeDetailsByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*model.UserWithStrikeDetails, error)) *UserRepo_GetUserWithStrikeDetailsByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByIDs provides a mock function for the type UserRepo
func (_mock *UserRepo) GetUsersByIDs(ctx context.Context, ids []string) ([]model.User, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByIDs")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]model.User, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []model.User); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_GetUsersByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByIDs'
type UserRepo_GetUsersByIDs_Call struct {
	*mock.Call
}

// GetUsersByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *UserRepo_Expecter) GetUsersByIDs(ctx interface{}, ids interface{}) *UserRepo_GetUsersByIDs_Call {
	return &UserRepo_GetUsersByIDs_Call{Call: _e.mock.On("GetUsersByIDs", ctx, ids)}
}

func (_c *UserRepo_GetUsersByIDs_Call) Run(run func(ctx context.Context, ids []string)) *UserRepo_GetUsersByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_GetUsersByIDs_Call) Return(users []model.User, err error) *UserRepo_GetUsersByIDs_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *UserRepo_GetUsersByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []string) ([]model.User, error)) *UserRepo_GetUsersByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersWithBirthday provides a mock function for the type UserRepo
func (_mock *UserRepo) GetUsersWithBirthday(ctx context.Context, date time.Time) ([]model.User, error) {
	ret := _mock.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithBirthday")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]model.User, error)); ok {
		return returnFunc(ctx, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []model.User); ok {
		r0 = returnFunc(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_GetUsersWithBirthday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersWithBirthday'
type UserRepo_GetUsersWithBirthday_Call struct {
	*mock.Call
}

// GetUsersWithBirthday is a helper method to define mock.On call
//   - ctx context.Context
//   - date time.Time
func (_e *UserRepo_Expecter) GetUsersWithBirthday(ctx interface{}, date interface{}) *UserRepo_GetUsersWithBirthday_Call {
	return &UserRepo_GetUsersWithBirthday_Call{Call: _e.mock.On("GetUsersWithBirthday", ctx, date)}
}

func (_c *UserRepo_GetUsersWithBirthday_Call) Run(run func(ctx context.Context, date time.Time)) *UserRepo_GetUsersWithBirthday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_GetUsersWithBirthday_Call) Return(users []model.User, err error) *UserRepo_GetUsersWithBirthday_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *UserRepo_GetUsersWithBirthday_Call) RunAndReturn(run func(ctx context.Context, date time.Time) ([]model.User, error)) *UserRepo_GetUsersWithBirthday_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersWithStrikeDetails provides a mock function for the type UserRepo
func (_mock *UserRepo) GetUsersWithStrikeDetails(ctx context.Context) ([]model.UserWithStrikeDetails, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithStrikeDetails")
	}

	var r0 []model.UserWithStrikeDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.UserWithStrikeDetails, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.UserWithStrikeDetails); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserWithStrikeDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_GetUsersWithStrikeDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersWithStrikeDetails'
type UserRepo_GetUsersWithStrikeDetails_Call struct {
	*mock.Call
}

// GetUsersWithStrikeDetails is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepo_Expecter) GetUsersWithStrikeDetails(ctx interface{}) *UserRepo_GetUsersWithStrikeDetails_Call {
	return &UserRepo_GetUsersWithStrikeDetails_Call{Call: _e.mock.On("GetUsersWithStrikeDetails", ctx)}
}

func (_c *UserRepo_GetUsersWithStrikeDetails_Call) Run(run func(ctx context.Context)) *UserRepo_GetUsersWithStrikeDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepo_GetUsersWithStrikeDetails_Call) Return(userWithStrikeDetailss []model.UserWithStrikeDetails, err error) *UserRepo_GetUsersWithStrikeDetails_Call {
	_c.Call.Return(userWithStrikeDetailss, err)
	return _c
}

func (_c *UserRepo_GetUsersWithStrikeDetails_Call) RunAndReturn(run func(ctx context.Context) ([]model.UserWithStrikeDetails, error)) *UserRepo_GetUsersWithStrikeDetails_Call {
	_c.Call.Return(run)
	return _c
}

// ResetUserYears provides a mock function for the type UserRepo
func (_mock *UserRepo) ResetUserYears(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetUserYears")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_ResetUserYears_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetUserYears'
type UserRepo_ResetUserYears_Call struct {
	*mock.Call
}

// ResetUserYears is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepo_Expecter) ResetUserYears(ctx interface{}) *UserRepo_ResetUserYears_Call {
	return &UserRepo_ResetUserYears_Call{Call: _e.mock.On("ResetUserYears", ctx)}
}

func (_c *UserRepo_ResetUserYears_Call) Run(run func(ctx context.Context)) *UserRepo_ResetUserYears_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepo_ResetUserYears_Call) Return(n int64, err error) *UserRepo_ResetUserYears_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UserRepo_ResetUserYears_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *UserRepo_ResetUserYears_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsersByName provides a mock function for the type UserRepo
func (_mock *UserRepo) SearchUsersByName(ctx context.Context, query string, limit int) ([]model.User, error) {
	ret := _mock.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsersByName")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]model.User, error)); ok {
		return returnFunc(ctx, query, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []model.User); ok {
		r0 = returnFunc(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_SearchUsersByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsersByName'
type UserRepo_SearchUsersByName_Call struct {
	*mock.Call
}

// SearchUsersByName is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
func (_e *UserRepo_Expecter) SearchUsersByName(ctx interface{}, query interface{}, limit interface{}) *UserRepo_SearchUsersByName_Call {
	return &UserRepo_SearchUsersByName_Call{Call: _e.mock.On("SearchUsersByName", ctx, query, limit)}
}

func (_c *UserRepo_SearchUsersByName_Call) Run(run func(ctx context.Context, query string, limit int)) *UserRepo_SearchUsersByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepo_SearchUsersByName_Call) Return(users []model.User, err error) *UserRepo_SearchUsersByName_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *UserRepo_SearchUsersByName_Call) RunAndReturn(run func(ctx context.Context, query string, limit int) ([]model.User, error)) *UserRepo_SearchUsersByName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserImage provides a mock function for the type UserRepo
func (_mock *UserRepo) UpdateUserImage(ctx context.Context, userID string, hasImage bool) error {
	ret := _mock.Called(ctx, userID, hasImage)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, userID, hasImage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_UpdateUserImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserImage'
type UserRepo_UpdateUserImage_Call struct {
	*mock.Call
}

// UpdateUserImage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - hasImage bool
func (_e *UserRepo_Expecter) UpdateUserImage(ctx interface{}, userID interface{}, hasImage interface{}) *UserRepo_UpdateUserImage_Call {
	return &UserRepo_UpdateUserImage_Call{Call: _e.mock.On("UpdateUserImage", ctx, userID, hasImage)}
}

func (_c *UserRepo_UpdateUserImage_Call) Run(run func(ctx context.Context, userID string, hasImage bool)) *UserRepo_UpdateUserImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepo_UpdateUserImage_Call) Return(err error) *UserRepo_UpdateUserImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_UpdateUserImage_Call) RunAndReturn(run func(ctx context.Context, userID string, hasImage bool) error) *UserRepo_UpdateUserImage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserLastSignIn provides a mock function for the type UserRepo
func (_mock *UserRepo) UpdateUserLastSignIn(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserLastSignIn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_UpdateUserLastSignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserLastSignIn'
type UserRepo_UpdateUserLastSignIn_Call struct {
	*mock.Call
}

// UpdateUserLastSignIn is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserRepo_Expecter) UpdateUserLastSignIn(ctx interface{}, userID interface{}) *UserRepo_UpdateUserLastSignIn_Call {
	return &UserRepo_UpdateUserLastSignIn_Call{Call: _e.mock.On("UpdateUserLastSignIn", ctx, userID)}
}

func (_c *UserRepo_UpdateUserLastSignIn_Call) Run(run func(ctx context.Context, userID string)) *UserRepo_UpdateUserLastSignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_UpdateUserLastSignIn_Call) Return(err error) *UserRepo_UpdateUserLastSignIn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_UpdateUserLastSignIn_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *UserRepo_UpdateUserLastSignIn_Call {
	_c.Call.Return(run)
	return _c
}
