// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uno/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NewVerificationTokenRepo creates a new instance of VerificationTokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationTokenRepo {
	mock := &VerificationTokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VerificationTokenRepo is an autogenerated mock type for the VerificationTokenRepo type
type VerificationTokenRepo struct {
	mock.Mock
}

type VerificationTokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *VerificationTokenRepo) EXPECT() *VerificationTokenRepo_Expecter {
	return &VerificationTokenRepo_Expecter{mock: &_m.Mock}
}

// CreateVerificationToken provides a mock function for the type VerificationTokenRepo
func (_mock *VerificationTokenRepo) CreateVerificationToken(ctx context.Context, token model.VerificationToken) (model.VerificationToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerificationToken")
	}

	var r0 model.VerificationToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.VerificationToken) (model.VerificationToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.VerificationToken) model.VerificationToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(model.VerificationToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.VerificationToken) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VerificationTokenRepo_CreateVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerificationToken'
type VerificationTokenRepo_CreateVerificationToken_Call struct {
	*mock.Call
}

// CreateVerificationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token model.VerificationToken
func (_e *VerificationTokenRepo_Expecter) CreateVerificationToken(ctx interface{}, token interface{}) *VerificationTokenRepo_CreateVerificationToken_Call {
	return &VerificationTokenRepo_CreateVerificationToken_Call{Call: _e.mock.On("CreateVerificationToken", ctx, token)}
}

func (_c *VerificationTokenRepo_CreateVerificationToken_Call) Run(run func(ctx context.Context, token model.VerificationToken)) *VerificationTokenRepo_CreateVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.VerificationToken
		if args[1] != nil {
			arg1 = args[1].(model.VerificationToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VerificationTokenRepo_CreateVerificationToken_Call) Return(verificationToken model.VerificationToken, err error) *VerificationTokenRepo_CreateVerificationToken_Call {
	_c.Call.Return(verificationToken, err)
	return _c
}

func (_c *VerificationTokenRepo_CreateVerificationToken_Call) RunAndReturn(run func(ctx context.Context, token model.VerificationToken) (model.VerificationToken, error)) *VerificationTokenRepo_CreateVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVerificationToken provides a mock function for the type VerificationTokenRepo
func (_mock *VerificationTokenRepo) DeleteVerificationToken(ctx context.Context, identifier string, token string) error {
	ret := _mock.Called(ctx, identifier, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVerificationToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, identifier, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VerificationTokenRepo_DeleteVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVerificationToken'
type VerificationTokenRepo_DeleteVerificationToken_Call struct {
	*mock.Call
}

// DeleteVerificationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - token string
func (_e *VerificationTokenRepo_Expecter) DeleteVerificationToken(ctx interface{}, identifier interface{}, token interface{}) *VerificationTokenRepo_DeleteVerificationToken_Call {
	return &VerificationTokenRepo_DeleteVerificationToken_Call{Call: _e.mock.On("DeleteVerificationToken", ctx, identifier, token)}
}

func (_c *VerificationTokenRepo_DeleteVerificationToken_Call) Run(run func(ctx context.Context, identifier string, token string)) *VerificationTokenRepo_DeleteVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VerificationTokenRepo_DeleteVerificationToken_Call) Return(err error) *VerificationTokenRepo_DeleteVerificationToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VerificationTokenRepo_DeleteVerificationToken_Call) RunAndReturn(run func(ctx context.Context, identifier string, token string) error) *VerificationTokenRepo_DeleteVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAndMarkTokenAsUsed provides a mock function for the type VerificationTokenRepo
func (_mock *VerificationTokenRepo) GetAndMarkTokenAsUsed(ctx context.Context, identifier string, token string) (model.VerificationToken, error) {
	ret := _mock.Called(ctx, identifier, token)

	if len(ret) == 0 {
		panic("no return value specified for GetAndMarkTokenAsUsed")
	}

	var r0 model.VerificationToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.VerificationToken, error)); ok {
		return returnFunc(ctx, identifier, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.VerificationToken); ok {
		r0 = returnFunc(ctx, identifier, token)
	} else {
		r0 = ret.Get(0).(model.VerificationToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, identifier, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VerificationTokenRepo_GetAndMarkTokenAsUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndMarkTokenAsUsed'
type VerificationTokenRepo_GetAndMarkTokenAsUsed_Call struct {
	*mock.Call
}

// GetAndMarkTokenAsUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - token string
func (_e *VerificationTokenRepo_Expecter) GetAndMarkTokenAsUsed(ctx interface{}, identifier interface{}, token interface{}) *VerificationTokenRepo_GetAndMarkTokenAsUsed_Call {
	return &VerificationTokenRepo_GetAndMarkTokenAsUsed_Call{Call: _e.mock.On("GetAndMarkTokenAsUsed", ctx, identifier, token)}
}

func (_c *VerificationTokenRepo_GetAndMarkTokenAsUsed_Call) Run(run func(ctx context.Context, identifier string, token string)) *VerificationTokenRepo_GetAndMarkTokenAsUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VerificationTokenRepo_GetAndMarkTokenAsUsed_Call) Return(verificationToken model.VerificationToken, err error) *VerificationTokenRepo_GetAndMarkTokenAsUsed_Call {
	_c.Call.Return(verificationToken, err)
	return _c
}

func (_c *VerificationTokenRepo_GetAndMarkTokenAsUsed_Call) RunAndReturn(run func(ctx context.Context, identifier string, token string) (model.VerificationToken, error)) *VerificationTokenRepo_GetAndMarkTokenAsUsed_Call {
	_c.Call.Return(run)
	return _c
}

// GetVerificationToken provides a mock function for the type VerificationTokenRepo
func (_mock *VerificationTokenRepo) GetVerificationToken(ctx context.Context, identifier string, token string) (model.VerificationToken, error) {
	ret := _mock.Called(ctx, identifier, token)

	if len(ret) == 0 {
		panic("no return value specified for GetVerificationToken")
	}

	var r0 model.VerificationToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.VerificationToken, error)); ok {
		return returnFunc(ctx, identifier, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.VerificationToken); ok {
		r0 = returnFunc(ctx, identifier, token)
	} else {
		r0 = ret.Get(0).(model.VerificationToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, identifier, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VerificationTokenRepo_GetVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVerificationToken'
type VerificationTokenRepo_GetVerificationToken_Call struct {
	*mock.Call
}

// GetVerificationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - token string
func (_e *VerificationTokenRepo_Expecter) GetVerificationToken(ctx interface{}, identifier interface{}, token interface{}) *VerificationTokenRepo_GetVerificationToken_Call {
	return &VerificationTokenRepo_GetVerificationToken_Call{Call: _e.mock.On("GetVerificationToken", ctx, identifier, token)}
}

func (_c *VerificationTokenRepo_GetVerificationToken_Call) Run(run func(ctx context.Context, identifier string, token string)) *VerificationTokenRepo_GetVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VerificationTokenRepo_GetVerificationToken_Call) Return(verificationToken model.VerificationToken, err error) *VerificationTokenRepo_GetVerificationToken_Call {
	_c.Call.Return(verificationToken, err)
	return _c
}

func (_c *VerificationTokenRepo_GetVerificationToken_Call) RunAndReturn(run func(ctx context.Context, identifier string, token string) (model.VerificationToken, error)) *VerificationTokenRepo_GetVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTokenAsUsed provides a mock function for the type VerificationTokenRepo
func (_mock *VerificationTokenRepo) MarkTokenAsUsed(ctx context.Context, identifier string, token string) error {
	ret := _mock.Called(ctx, identifier, token)

	if len(ret) == 0 {
		panic("no return value specified for MarkTokenAsUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, identifier, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VerificationTokenRepo_MarkTokenAsUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTokenAsUsed'
type VerificationTokenRepo_MarkTokenAsUsed_Call struct {
	*mock.Call
}

// MarkTokenAsUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - token string
func (_e *VerificationTokenRepo_Expecter) MarkTokenAsUsed(ctx interface{}, identifier interface{}, token interface{}) *VerificationTokenRepo_MarkTokenAsUsed_Call {
	return &VerificationTokenRepo_MarkTokenAsUsed_Call{Call: _e.mock.On("MarkTokenAsUsed", ctx, identifier, token)}
}

func (_c *VerificationTokenRepo_MarkTokenAsUsed_Call) Run(run func(ctx context.Context, identifier string, token string)) *VerificationTokenRepo_MarkTokenAsUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VerificationTokenRepo_MarkTokenAsUsed_Call) Return(err error) *VerificationTokenRepo_MarkTokenAsUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VerificationTokenRepo_MarkTokenAsUsed_Call) RunAndReturn(run func(ctx context.Context, identifier string, token string) error) *VerificationTokenRepo_MarkTokenAsUsed_Call {
	_c.Call.Return(run)
	return _c
}
