ktor:
    development: true
    application:
        modules:
            - no.uib.echo.ApplicationKt.module
    deployment:
        port: 8080

postgres:
  url: "jdbc:postgresql://localhost/echo-web"
  user: postgres
  password: postgres