#:schema node_modules/wrangler/config-schema.json
name = "echo-web-api"
main = "src/index.ts"
compatibility_date = "2024-09-28"
compatibility_flags = ["nodejs_compat_v2"]

workers_dev = false

[observability]
enabled = true


[[hyperdrive]]
id = "58469bacdcc346ebbdd994271097d2fd"
binding = "HYPERDRIVE"
localConnectionString = "postgres://postgres:postgres@localhost:5432/echo-web"
