name: Check types

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  type-check:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://admin:password@localhost:5432/postgres
      FEIDE_CLIENT_ID: ${{ secrets.FEIDE_CLIENT_ID }}
      FEIDE_CLIENT_SECRET: ${{ secrets.FEIDE_CLIENT_SECRET }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-install

      - run: pnpm db:generate

      - run: pnpm type-check
