name: Test migrations

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test-migrations:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://admin:password@localhost:5432/postgres
      FEIDE_CLIENT_ID: ${{ secrets.FEIDE_CLIENT_ID }}
      FEIDE_CLIENT_SECRET: ${{ secrets.FEIDE_CLIENT_SECRET }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-install

      - name: Set up Prisma
        run: pnpm install -g prisma

      - name: Test migrations
        run: |
          prisma migrate dev --schema ./packages/db/prisma/schema.prisma
          prisma migrate reset --force --schema ./packages/db/prisma/schema.prisma
          prisma migrate deploy --schema ./packages/db/prisma/schema.prisma
          prisma generate --schema ./packages/db/prisma/schema.prisma
